export const apiEndpoints = {
  admin: {
    login: "/api/Admin/login",
    create: "/api/Admin",
    getAll: "/api/Admin",
    getById: (adminId) => `/api/Admin/${adminId}`,
    changePassword: "/api/Admin/change-password",
    updateStatus: (adminId) => `/api/Admin/${adminId}/status`,
  },
  assignments: {
    list: "/api/v1/assignments",
    adminList: "/api/admin/assignments",
    adminCreate: "/api/admin/assignments",
    create: "/api/v1/assignments",
    details: (id) => `/api/v1/assignments/${id}`,
    update: (id) => `/api/v1/assignments/${id}`,
    delete: (id) => `/api/v1/assignments/${id}`,
    submit: (id) => `/api/v1/assignments/${id}/submit`,
    subjectsByGroup: (groupId) => `/api/v1/assignments/groups/${groupId}/subjects`,
    submissions: (id) => `/api/v1/assignments/${id}/submissions`,
  },
  faculty: {
    list: "/api/v1/faculty",
    getAll: "/api/v1/faculty",
    create: "/api/v1/faculty",
    getById: (id) => `/api/v1/faculty/${id}`,
    update: (id) => `/api/v1/faculty/${id}`,
    delete: (id) => `/api/v1/faculty/${id}`,
    uploadPhoto: "/api/v1/faculty/upload-photo",
    getPhoto: (id) => `/api/v1/faculty/photo/${id}`,
    assignSubject: "/api/v1/faculty/assign-subject",
    updateSubjectAssignment: (id) => `/api/v1/faculty/assign-subject/${id}`,
    deleteSubjectAssignment: (id) => `/api/v1/faculty/assign-subject/${id}`,
    getWorkload: (facultyId) => `/api/v1/faculty/workload/${facultyId}`,
  },
  boards: {
    list: "/api/v1/boards",
    getAll: "/api/v1/boards",
    getAcademicLevels: "/api/v1/boards/academic-levels",
  },
  academicYears: {
    list: "/api/v1/academic-years",
    getAll: "/api/v1/academic-years",
    create: "/api/v1/academic-years",
    getById: (yearId) => `/api/v1/academic-years/${yearId}`,
    update: (yearId) => `/api/v1/academic-years/${yearId}`,
    delete: (yearId) => `/api/v1/academic-years/${yearId}`,
    activate: (yearId) => `/api/v1/academic-years/${yearId}/activate`,
  },
  groups: {
    getAll: "/api/v1/groups",
    list: "/api/v1/groups",
    listPage: "/api/v1/groups",
    create: "/api/v1/groups",
    getById: (groupId) => `/api/v1/groups/${groupId}`,
    update: (groupId) => `/api/v1/groups/${groupId}`,
    delete: (groupId) => `/api/v1/groups/${groupId}`,
    getByBoard: (board) => `/api/v1/groups/board/${board}`,
    validateCode: "/api/v1/groups/validate-code",
  },
  fee: {
    createStructure: "/api/Fee/structure",
    getStructures: "/api/Fee/structure",
    updateStructure: (id) => `/api/Fee/structure/${id}`,
    assign: "/api/Fee/assign",
    collect: "/api/Fee/collect",
    getStudentFees: (studentId) => `/api/Fee/student/${studentId}`,
    updatePayment: (id) => `/api/Fee/payment/${id}`,
    deletePayment: (id) => `/api/Fee/payment/${id}`,
    addDiscount: "/api/Fee/discount",
    addFine: "/api/Fee/fine",
    waiveFine: (id) => `/api/Fee/fine/${id}/waive`,
    getReceipt: (receiptId) => `/api/Fee/receipt/${receiptId}`,
    addScholarship: "/api/Fee/scholarship",
    refund: "/api/Fee/refund",
    getDue: "/api/Fee/due",
    getHistory: (studentId) => `/api/Fee/history/${studentId}`,
    downloadReceipt: (feeCollectionId) => `/api/Fee/receipt/download/${feeCollectionId}`,
    dailyReport: "/api/Fee/report/daily",
    monthlyReport: "/api/Fee/report/monthly",
    outstandingReport: "/api/Fee/report/outstanding",
  },
  auth: {
    login: "/api/Auth/login",
    register: "/api/Auth/register",
    forgotPassword: "/api/Auth/forgot-password",
    verifyOtp: "/api/Auth/verify-otp",
    resetPassword: "/api/Auth/reset-password",
    users: "/api/Auth/users",
    userById: (id) => `/api/Auth/user/${id}`,
  },
  subjects: {
    getAll: "/api/Subjects",
    create: "/api/Subjects",
    getById: (id) => `/api/Subjects/${id}`,
    update: (id) => `/api/Subjects/${id}`,
    delete: (id) => `/api/Subjects/${id}`,
    getByGroup: (group) => `/api/Subjects/group/${encodeURIComponent(group)}`,
  },
  departments: {
    getAll: "/api/v1/departments",
  },
  sections: {
    getAll: "/api/v1/Sections",
    list: "/api/v1/Sections",
    create: "/api/v1/Sections",
    getById: (sectionId) => `/api/v1/Sections/${sectionId}`,
    update: (sectionId) => `/api/v1/Sections/${sectionId}`,
    delete: (sectionId) => `/api/v1/Sections/${sectionId}`,
    byGroup: (groupId) => `/api/v1/Sections/group/${groupId}`,
  },
  periods: {
    getAll: "/api/v1/periods",
  },
  rooms: {
    getAll: "/api/v1/rooms",
  },
  attendance: {
    create: "/api/v1/attendance/create",
    bulk: "/api/v1/attendance/bulk",
    update: "/api/v1/attendance/update",
    getById: (attendanceId) => `/api/v1/attendance/${attendanceId}`,
    search: "/api/v1/attendance/search",
    students: "/api/v1/attendance/students",
    summary: "/api/v1/attendance/summary",
    percentage: "/api/v1/attendance/percentage",
    report: "/api/v1/attendance/report",
    updateStatus: (attendanceId) => `/api/v1/attendance/${attendanceId}/status`,
  },
  students: {
    getAll: "/api/v1/students",
    create: "/api/v1/students",
    getById: (studentId) => `/api/v1/students/${studentId}`,
    update: (studentId) => `/api/v1/students/${studentId}`,
    delete: (studentId) => `/api/v1/students/${studentId}`,
    getProfile: (studentId) => `/api/v1/students/${studentId}/profile`,
    updateProfile: (studentId) => `/api/v1/students/${studentId}/profile`,
    updateSection: (studentId) => `/api/v1/students/${studentId}/section`,
    updateGroup: (studentId) => `/api/v1/students/${studentId}/group`,
    transfer: (studentId) => `/api/v1/students/${studentId}/transfer`,
    suspend: (studentId) => `/api/v1/students/${studentId}/suspend`,
    activate: (studentId) => `/api/v1/students/${studentId}/activate`,
    resetPassword: (studentId) => `/api/v1/students/${studentId}/reset-password`,
    getDashboard: (studentId) => `/api/v1/students/${studentId}/dashboard`,
  },
  certificates: {
    list: "/api/certificates",
    create: "/api/certificates",
    getById: (id) => `/api/certificates/${id}`,
    update: (id) => `/api/certificates/${id}`,
    delete: (id) => `/api/certificates/${id}`,
    bonafide: "/api/certificates/bonafide",
    study: "/api/certificates/study",
    conduct: "/api/certificates/conduct",
    fee: "/api/certificates/fee",
    tc: "/api/certificates/tc",
    history: "/api/certificates/history",
    download: (id) => `/api/certificates/download/${id}`,
    verify: (certificateNo) => `/api/certificates/verify/${encodeURIComponent(certificateNo)}`,
    reissue: "/api/certificates/reissue",
    cancel: (id) => `/api/certificates/${id}/cancel`,
    review: (id) => `/api/certificates/${id}/review`,
    approve: (id) => `/api/certificates/${id}/approve`,
    issue: (id) => `/api/certificates/${id}/issue`,
  },
  timetable: {
    getAll: "/api/v1/timetable",
    create: "/api/v1/timetable",
    getById: (id) => `/api/v1/timetable/${id}`,
    update: (id) => `/api/v1/timetable/${id}`,
    delete: (id) => `/api/v1/timetable/${id}`,
    getAllocatedFaculties: "/api/v1/timetable/allocated-faculties",
    getByFaculty: (facultyId) => `/api/v1/timetable/faculty/${facultyId}`,
    getByStudent: (studentId) => `/api/v1/timetable/student/${studentId}`,
    getBySection: (sectionId) => `/api/v1/timetable/section/${sectionId}`,
    copy: "/api/v1/timetable/copy",
    publish: (id) => `/api/v1/timetable/${id}/publish`,
    publishSection: (sectionId) => `/api/v1/timetable/section/${sectionId}/publish`,
  },
  reports: {
    dashboard: "/api/reports/dashboard",
    summary: "/api/reports/summary",
    admissions: "/api/reports/admissions",
    studentStrength: "/api/reports/student-strength",
    attendance: "/api/reports/attendance",
    facultyAttendance: "/api/reports/faculty-attendance",
    feeCollection: "/api/reports/fees/collection",
    feeOutstanding: "/api/reports/fees/outstanding",
    examinations: "/api/reports/examinations",
    results: "/api/reports/results",
    passPercentage: "/api/reports/pass-percentage",
    toppers: "/api/reports/toppers",
    subjects: "/api/reports/subjects",
    groups: "/api/reports/groups",
    sections: "/api/reports/sections",
    facultyWorkload: "/api/reports/faculty-workload",
    studentPerformance: "/api/reports/student-performance",
    auditLogs: "/api/reports/audit-logs",
    exportPdf: "/api/reports/export/pdf",
    exportExcel: "/api/reports/export/excel",
    custom: "/api/reports/custom",
  },
};
