export const apiEndpoints = {
  admin: {
    login: "/api/Admin/login",
    create: "/api/Admin",
    getAll: "/api/Admin",
    getById: (adminId) => `/api/Admin/${adminId}`,
    changePassword: "/api/Admin/change-password",
    updateStatus: (adminId) => `/api/Admin/${adminId}/status`,
  },
  assignments: {
    list: "/api/v1/assignments",
    published: "/api/v1/assignments/published",
    adminList: "/api/admin/assignments",
    adminCreate: "/api/admin/assignments",
    create: "/api/v1/assignments",
    details: (id) => `/api/v1/assignments/${id}`,
    update: (id) => `/api/v1/assignments/${id}`,
    delete: (id) => `/api/v1/assignments/${id}`,
    submit: (id) => `/api/v1/assignments/${id}/submit`,
    // Backend contract: POST { assignmentIds: number[] } to publish selected assignments.
    bulkPublish: "/api/v1/assignments/publish",
    subjectsByGroup: (groupId) => `/api/v1/assignments/groups/${groupId}/subjects`,
    facultyDropdown: "/api/v1/assignments/faculty-dropdown",
    submissions: (id) => `/api/admin/assignments/${id}/submissions`,
  },
  faculty: {
    list: "/api/v1/staff",
    getAll: "/api/v1/staff",
    create: "/api/v1/staff",
    getById: (id) => `/api/v1/staff/${id}`,
    update: (id) => `/api/v1/staff/${id}`,
    delete: (id) => `/api/v1/staff/${id}`,
    uploadPhoto: "/api/v1/staff/upload-photo",
    getPhoto: (id) => `/api/v1/staff/photo/${id}`,
    assignSubject: "/api/v1/staff/assign-subject",
    updateSubjectAssignment: (id) => `/api/v1/staff/assign-subject/${id}`,
    deleteSubjectAssignment: (id) => `/api/v1/staff/assign-subject/${id}`,
    getWorkload: (facultyId) => `/api/v1/staff/workload/${facultyId}`,
    // Existing assignment faculty dropdown endpoint; subject IDs are supplied as query params by the caller.
    bySubjects: "/api/v1/assignments/faculty-dropdown",
  },
  boards: {
    list: "/api/v1/boards",
    getAll: "/api/v1/boards",
    create: "/api/v1/boards",
    getById: (boardId) => `/api/v1/boards/${boardId}`,
    update: (boardId) => `/api/v1/boards/${boardId}`,
    delete: (boardId) => `/api/v1/boards/${boardId}`,
    getAcademicLevels: "/api/v1/boards/academic-levels",
    academicLevels: "/api/v1/boards/academic-levels",
    gradingSystems: "/api/v1/boards/grading-systems",
    validateBoardCode: "/api/v1/boards/validate-board-code",
    formData: "/api/v1/boards/form-data",
    states: (countryId) => `/api/v1/boards/states/${countryId}`,
    history: (boardId) => `/api/v1/boards/${boardId}/history`,
    summary: "/api/v1/boards/summary",
  },
  academicYears: {
    list: "/api/v1/academic-years",
    getAll: "/api/v1/academic-years",
    active: "/api/v1/academic-years/active",
    create: "/api/v1/academic-years",
    getById: (yearId) => `/api/v1/academic-years/${yearId}`,
    update: (yearId) => `/api/v1/academic-years/${yearId}`,
    delete: (yearId) => `/api/v1/academic-years/${yearId}`,
    activate: (yearId) => `/api/v1/academic-years/${yearId}/activate`,
  },
  breakTypes: {
    list: "/api/v1/break-types",
  },
  groups: {
    getAll: "/api/v1/groups",
    dropdown: "/api/v1/groups/dropdown",
    list: "/api/v1/groups",
    listPage: "/api/v1/groups",
    create: "/api/v1/groups",
    getById: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}`,
    update: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}`,
    delete: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}`,
    students: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/students`,
    subjects: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/subjects`,
    programs: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/programs`,
    getPrograms: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/programs`,
    summary: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/summary`,
    getByBoard: (boardId) => `/api/v1/groups/board/${encodeURIComponent(boardId)}`,
    activate: (groupId) => `/api/v1/groups/${encodeURIComponent(groupId)}/activate`,
    validateCode: "/api/v1/groups/validate-code",
  },
  fee: {
    feeTypes: "/api/fees/types",
    createStructure: "/api/fees/structure",
    getStructures: "/api/fees/structure",
    getStructureById: (id) => `/api/fees/structure/${id}`,
    updateStructure: (id) => `/api/fees/structure/${id}`,
    deleteStructure: (id) => `/api/fees/structure/${id}`,
    assign: "/api/fees/assign",
    getStudentFees: (studentId) => `/api/fees/student/${studentId}`,
    getAssignment: (id) => `/api/fees/assignment/${id}`,
    updateAssignment: (id) => `/api/fees/assignment/${id}`,
    collect: "/api/fees/collect",
    getHistory: (studentId) => `/api/fees/history/${studentId}`,
    getReceipt: (receiptId) => `/api/fees/receipt/${receiptId}`,
    deletePayment: (id) => `/api/fees/payment/${id}`,
    addDiscount: "/api/fees/discount",
    addScholarship: "/api/fees/scholarship",
    addFine: "/api/fees/fine",
    waiveFine: (id) => `/api/fees/fine/${id}/waive`,
    refund: "/api/fees/refund",
    getDue: "/api/fees/due",
    admissionAssign: "/api/fees/admission/assign",
    admissionSummary: (admissionId) => `/api/fees/admission/${admissionId}/summary`,
    admissionPayment: (admissionId) => `/api/fees/admission/${admissionId}/payment`,
    downloadReceipt: (feeCollectionId) => `/api/fees/receipt/download/${feeCollectionId}`,
    dailyReport: "/api/fees/report/daily",
    monthlyReport: "/api/fees/report/monthly",
    outstandingReport: "/api/fees/report/outstanding",
  },
  auth: {
    login: "/api/Auth/login",
    register: "/api/Auth/register",
    forgotPassword: "/api/Auth/forgot-password",
    verifyOtp: "/api/Auth/verify-otp",
    resetPassword: "/api/Auth/reset-password",
    users: "/api/Auth/users",
    userById: (id) => `/api/Auth/user/${id}`,
  },
  results: {
    list: "/api/v1/results",
    process: "/api/v1/results/process",
    publish: "/api/v1/results/publish",
    byStudent: (studentId) => `/api/v1/results/students/${studentId}`,
    studentResult: "/api/v1/results/student-result",
    rankList: "/api/v1/results/rank-list",
    failedStudents: "/api/v1/results/failed-students",
    statistics: "/api/v1/results/statistics",
    analysis: "/api/v1/results/analysis",
    exportExcel: "/api/v1/results/export-excel",
    downloadPdf: "/api/v1/results/download-pdf",
    studentMemo: "/api/v1/results/students/memo",
    memo: (studentId) => `/api/v1/results/memo/${studentId}`,
    revaluation: "/api/v1/results/revaluation",
    revaluationById: (revaluationId) => `/api/v1/results/revaluation/${revaluationId}`,
  },
  subjects: {
    getAll: "/api/Subjects",
    search: "/api/Subjects/search",
    context: "/api/Subjects/context",
    getActive: "/api/Subjects/active",
    getByBoard: (boardId) => `/api/Subjects/board/${encodeURIComponent(boardId)}`,
    getByAcademicYear: (academicYearId) => `/api/Subjects/academic-year/${encodeURIComponent(academicYearId)}`,
    checkCode: "/api/Subjects/check-code",
    create: "/api/Subjects",
    getById: (id) => `/api/Subjects/${id}`,
    update: (id) => `/api/Subjects/${id}`,
    delete: (id) => `/api/Subjects/${id}`,
    getByGroup: (groupId) => `/api/Subjects/group/${encodeURIComponent(groupId)}`,
  },
  departments: {
    getAll: "/api/v1/departments",
  },
  sections: {
    getAll: "/api/v1/Sections",
    list: "/api/v1/Sections",
    create: "/api/v1/Sections",
    getById: (sectionId) => `/api/v1/Sections/${sectionId}`,
    update: (sectionId) => `/api/v1/Sections/${sectionId}`,
    delete: (sectionId) => `/api/v1/Sections/${sectionId}`,
    byGroup: (groupId) => `/api/v1/Sections/group/${groupId}`,
    search: "/api/v1/Sections",
  },
  periods: {
    getAll: "/api/v1/periods",
    create: "/api/v1/periods",
    getById: (id) => `/api/v1/periods/${id}`,
    update: (id) => `/api/v1/periods/${id}`,
    delete: (id) => `/api/v1/periods/${id}`,
  },
  periodStructures: {
    list: "/api/v1/period-structures",
    create: "/api/v1/period-structures",
    getById: (id) => `/api/v1/period-structures/${id}`,
    update: (id) => `/api/v1/period-structures/${id}`,
    delete: (id) => `/api/v1/period-structures/${id}`,
    preview: "/api/v1/period-structures/preview",
    assign: (id) => `/api/v1/period-structures/${id}/assign`,
    context: "/api/v1/period-structures/context",
  },
  rooms: {
    getAll: "/api/v1/rooms",
  },
  attendance: {
    create: "/api/v1/attendance/create",
    bulk: "/api/v1/attendance/bulk",
    update: "/api/v1/attendance/update",
    bulkUpdate: "/api/v1/attendance/bulk-update",
    delete: (attendanceId) => `/api/v1/attendance/${attendanceId}`,
    getById: (attendanceId) => `/api/v1/attendance/${attendanceId}`,
    search: "/api/v1/attendance/search",
    students: "/api/v1/attendance/students",
    facultySubject: "/api/v1/attendance/faculty-subject",
    academicContext: "/api/v1/attendance/academic-context",
    studentMonthlyReport: "/api/v1/attendance/student-monthly-report",
    studentMonthlyExport: "/api/v1/attendance/student-monthly-report/export/excel",
    summary: "/api/v1/attendance/summary",
    percentage: "/api/v1/attendance/percentage",
    report: "/api/v1/attendance/report",
    updateStatus: (attendanceId) => `/api/v1/attendance/${attendanceId}/status`,
    lockSession: (sessionId) => `/api/v1/attendance/session/${sessionId}/lock`,
    unlockSession: (sessionId) => `/api/v1/attendance/session/${sessionId}/unlock`,
  },
  staffAttendance: {
    load: "/api/v1/staff-attendance/load",
    bulk: "/api/v1/staff-attendance/bulk",
    details: (facultyId) => `/api/v1/staff-attendance/staff/${facultyId}/details`,
    monthlyReport: "/api/v1/staff-attendance/monthly-report",
    monthlyExport: "/api/v1/staff-attendance/monthly-report/export/excel",
  },
  students: {
    getAll: "/api/v1/students",
    getById: (studentId) => `/api/v1/students/${studentId}`,
    update: (studentId) => `/api/v1/students/${studentId}`,
    delete: (studentId) => `/api/v1/students/${studentId}`,
    getProfile: (studentId) => `/api/v1/students/${studentId}/profile`,
    updateProfile: (studentId) => `/api/v1/students/${studentId}/profile`,
    updateSection: (studentId) => `/api/v1/students/${studentId}/section`,
    updateGroup: (studentId) => `/api/v1/students/${studentId}/group`,
    transfer: (studentId) => `/api/v1/students/${studentId}/transfer`,
    suspend: (studentId) => `/api/v1/students/${studentId}/suspend`,
    activate: (studentId) => `/api/v1/students/${studentId}/activate`,
    resetPassword: (studentId) => `/api/v1/students/${studentId}/reset-password`,
    getDashboard: (studentId) => `/api/v1/students/${studentId}/dashboard`,
    search: "/api/v1/students/search",
    getActive: "/api/v1/students/active",
    getByGroup: (groupId) => `/api/v1/students/group/${groupId}`,
    getBySection: (sectionId) => `/api/v1/students/section/${sectionId}`,
    checkEmail: "/api/v1/students/check-email",
    checkMobile: "/api/v1/students/check-mobile",
  },
  admissions: {
    getAll: "/api/v1/admissions",
    create: "/api/v1/admissions",
    getById: (admissionId) => `/api/v1/admissions/${admissionId}`,
    update: (admissionId) => `/api/v1/admissions/${admissionId}`,
    delete: (admissionId) => `/api/v1/admissions/${admissionId}`,
    submit: (admissionId) => `/api/v1/admissions/${admissionId}/submit`,
    verify: (admissionId) => `/api/v1/admissions/${admissionId}/verify`,
    generateNumber: "/api/v1/admissions/generate-number",
    bloodGroups: "/api/v1/admissions/blood-groups",
    approve: (admissionId) => `/api/v1/admissions/${admissionId}/approve`,
    reject: (admissionId) => `/api/v1/admissions/${admissionId}/reject`,
  },
  location: {
    byPincode: (pincode) => `/api/v1/locations/pincode/${encodeURIComponent(pincode)}`,
  },
  certificates: {
    list: "/api/certificates",
    create: "/api/certificates",
    getById: (id) => `/api/certificates/${id}`,
    update: (id) => `/api/certificates/${id}`,
    delete: (id) => `/api/certificates/${id}`,
    bonafide: "/api/certificates/bonafide",
    study: "/api/certificates/study",
    conduct: "/api/certificates/conduct",
    fee: "/api/certificates/fee",
    tc: "/api/certificates/tc",
    other: "/api/certificates/other",
    history: "/api/certificates/history",
    download: (id) => `/api/certificates/download/${id}`,
    verify: (certificateNo) => `/api/certificates/verify/${encodeURIComponent(certificateNo)}`,
    reissue: "/api/certificates/reissue",
    cancel: (id) => `/api/certificates/${id}/cancel`,
    review: (id) => `/api/certificates/${id}/review`,
    approve: (id) => `/api/certificates/${id}/approve`,
    issue: (id) => `/api/certificates/${id}/issue`,
  },
  examinations: {
    getAll: "/api/v1/examinations",
  },
  timetable: {
    getAll: "/api/v1/timetable",
    create: "/api/v1/timetable",
    getById: (id) => `/api/v1/timetable/${id}`,
    update: (id) => `/api/v1/timetable/${id}`,
    delete: (id) => `/api/v1/timetable/${id}`,
    getAllocatedFaculties: "/api/v1/timetable/allocated-faculties",
    getByFaculty: (facultyId) => `/api/v1/timetable/faculty/${facultyId}`,
    getByStudent: (studentId) => `/api/v1/timetable/student/${studentId}`,
    getBySection: (sectionId) => `/api/v1/timetable/section/${sectionId}`,
    allocatedStaff: "/api/v1/timetable/allocated-staff",
    copy: "/api/v1/timetable/copy",
    publish: (id) => `/api/v1/timetable/${id}/publish`,
    publishSection: (sectionId) => `/api/v1/timetable/section/${sectionId}/publish`,
    approveSection: (sectionId) => `/api/v1/timetable/section/${sectionId}/approve`,
    validateSection: (sectionId) => `/api/v1/timetable/section/${sectionId}/validate`,
    generate: "/api/v1/timetable/generate",
  },
  promotions: {
    eligible: "/api/promotions/eligible",
    preview: "/api/promotions/preview",
    create: "/api/promotions",
    student: (studentId) => `/api/promotions/student/${studentId}`,
    groupAllocation: "/api/promotions/group-allocation",
    sectionAllocation: "/api/promotions/section-allocation",
    history: "/api/promotions/history",
    rollback: "/api/promotions/rollback",
    report: "/api/promotions/report",
  },
  reports: {
    dashboard: "/api/reports/dashboard",
    summary: "/api/reports/summary",
    admissions: "/api/reports/admissions",
    studentStrength: "/api/reports/student-strength",
    attendance: "/api/reports/attendance",
    facultyAttendance: "/api/reports/faculty-attendance",
    feeCollection: "/api/reports/fees/collection",
    feeOutstanding: "/api/reports/fees/outstanding",
    examinations: "/api/reports/examinations",
    results: "/api/reports/results",
    passPercentage: "/api/reports/pass-percentage",
    toppers: "/api/reports/toppers",
    subjects: "/api/reports/subjects",
    groups: "/api/reports/groups",
    sections: "/api/reports/sections",
    facultyWorkload: "/api/reports/faculty-workload",
    studentPerformance: "/api/reports/student-performance",
    auditLogs: "/api/reports/audit-logs",
    exportPdf: "/api/reports/export/pdf",
    exportExcel: "/api/reports/export/excel",
    custom: "/api/reports/custom",
  },
};
