export const apiEndpoints = {
  admin: {
    login: "/api/Admin/login",
    create: "/api/Admin",
    getAll: "/api/Admin",
    getById: (adminId) => `/api/Admin/${adminId}`,
    changePassword: "/api/Admin/change-password",
    updateStatus: (adminId) => `/api/Admin/${adminId}/status`,
  },
  auth: {
    login: "/api/Auth/login",
    register: "/api/Auth/register",
    forgotPassword: "/api/Auth/forgot-password",
    verifyOtp: "/api/Auth/verify-otp",
    resetPassword: "/api/Auth/reset-password",
    users: "/api/Auth/users",
    userById: (id) => `/api/Auth/user/${id}`,
    user: (id) => `/api/Auth/user/${id}`,
  },
  groups: {
    list: "/api/v1/groups",
    create: "/api/v1/groups",
    detail: (groupId) => `/api/v1/groups/${groupId}`,
    update: (groupId) => `/api/v1/groups/${groupId}`,
    remove: (groupId) => `/api/v1/groups/${groupId}`,
    byBoard: (board) => `/api/v1/groups/board/${encodeURIComponent(board)}`,
    validateCode: "/api/v1/groups/validate-code",
  },
  boards: {
    list: "/api/v1/boards",
    create: "/api/v1/boards",
    detail: (boardId) => `/api/v1/boards/${boardId}`,
    update: (boardId) => `/api/v1/boards/${boardId}`,
    remove: (boardId) => `/api/v1/boards/${boardId}`,
    status: (boardId) => `/api/v1/boards/${boardId}/status`,
    countries: "/api/v1/boards/countries",
    states: (countryId) => `/api/v1/boards/states/${countryId}`,
    academicPatterns: "/api/v1/boards/academic-patterns",
    academicLevels: "/api/v1/boards/academic-levels",
    gradingSystems: "/api/v1/boards/grading-systems",
    validateCode: "/api/v1/boards/validate-board-code",
  },
  departments: {
    list: "/api/v1/departments",
  },
  faculty: {
    list: "/api/v1/faculty",
    create: "/api/v1/faculty",
    detail: (id) => `/api/v1/faculty/${id}`,
    update: (id) => `/api/v1/faculty/${id}`,
    remove: (id) => `/api/v1/faculty/${id}`,
    uploadPhoto: "/api/v1/faculty/upload-photo",
    photo: (id) => `/api/v1/faculty/photo/${id}`,
    dropdown: "/api/v1/faculty/dropdown",
    assignSubject: "/api/v1/faculty/assign-subject",
    assignment: (id) => `/api/v1/faculty/assign-subject/${id}`,
    workload: (facultyId) => `/api/v1/faculty/workload/${facultyId}`,
  },
  academicYears: {
    list: "/api/v1/academic-years",
  },
};
