import { useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { CalendarDays, Pencil } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import { Modal, Toast } from "@/components/common/Ui.jsx";
import { mockAcademicLevels, mockAcademicYears, mockBoards, mockGroups, mockSections, mockStaffAttendance, mockStudentAttendance } from "@/data/attendanceMockData.js";
import "./AttendancePage.css";

const studentStatuses = ["Present", "Absent", "Leave"];
const staffStatuses = [...studentStatuses, "Late"];
const studentViews = ["Attendance", "Monthly Report", "Defaulters"];
const staffViews = ["Attendance", "Monthly Report"];
const pct = (rows) => rows.length ? Math.round(rows.filter((r) => r.status === "Present").length * 100 / rows.length) : 0;
const time = () => new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
const Field = ({ label, children }) => <label className="att-field"><span>{label}</span>{children}</label>;
const periodStatusesFor = (student) => Array.from({ length: 7 }, (_, index) => { const seed = Number(student.rollNo) + index; return seed % 9 === 0 ? "Leave" : seed % 6 === 0 ? "Absent" : "Present"; });
function Select({ label, value, onChange, items, all }) { return <Field label={label}><select value={value} onChange={onChange}>{all && <option value="">{all}</option>}{items.map((x) => <option key={x.id ?? x} value={x.id ?? x}>{x.name ?? x}</option>)}</select></Field>; }

export default function AttendancePage() {
  const { area = "student" } = useParams(); const staffMode = area === "staff";
  const [students, setStudents] = useState(mockStudentAttendance); const [staff, setStaff] = useState(mockStaffAttendance); const [toast, setToast] = useState("");
  return <><DashboardLayout title={staffMode ? "Staff Attendance" : "Student Attendance"} subtitle={staffMode ? "View and manage teaching and non-teaching staff attendance" : "View and manage student attendance records"} breadcrumb={["Operations", "Attendance"]}><main className="attendance-module">{staffMode ? <AttendanceScreen staff records={staff} setRecords={setStaff} say={setToast} /> : <StudentAttendanceScreen records={students} setRecords={setStudents} say={setToast} />}</main></DashboardLayout><Toast message={toast} onClose={() => setToast("")} /></>;
}

function StudentAttendanceScreen({ records, setRecords, say }) {
  const [filters, setFilters] = useState({ date: "2026-09-02", board: "", year: "", level: "", group: "", section: "", status: "", view: "Attendance" });
 const [loaded, setLoaded] = useState(false); const [query, setQuery] = useState(""); const [editing, setEditing] = useState(null); const [changes, setChanges] = useState([]); const [periods, setPeriods] = useState({});
  const monthLabel = new Date(`${filters.date.slice(0, 7)}-01T00:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" }).replace(" ", ", ");
  const update = (key) => (event) => setFilters({ ...filters, [key]: event.target.value });
  const rows = records.filter((row) => row.date === filters.date && (!filters.board || String(row.boardId) === filters.board) && (!filters.year || String(row.academicYearId) === filters.year) && (!filters.level || String(row.academicLevelId) === filters.level) && (!filters.group || String(row.groupId) === filters.group) && (!filters.section || String(row.sectionId) === filters.section) && (!filters.status || row.status === filters.status));
  const students = Object.values(rows.reduce((all, row) => { const student = all[row.studentId] ||= { ...row, morning: null, afternoon: null }; student[row.session.toLowerCase()] = row; return all; }, {})).filter((student) => `${student.studentName} ${student.rollNo} ${student.admissionNo}`.toLowerCase().includes(query.toLowerCase()));
  const periodValues = (student) => periods[student.studentId] || periodStatusesFor(student);
  const save = () => {
    const sessionUpdates = [editing.student.morning, editing.student.afternoon].filter(Boolean).map((old, index) => ({ old, next: editing.sessions[index] }));
    const previousPeriods = periodValues(editing.student);
    const changesToSave = [...sessionUpdates.flatMap(({ old, next }) => old.status !== next ? [{ label: old.session, oldStatus: old.status, newStatus: next }] : []), ...editing.periods.flatMap((status, index) => status !== previousPeriods[index] ? [{ label: `Period ${index + 1}`, oldStatus: previousPeriods[index], newStatus: status }] : [])];
    if (!changesToSave.length) return setEditing(null);
    if (!editing.remark?.trim()) return say("Reason / remark is required when attendance changes.");
    const changedAt = time();
    setRecords(records.map((row) => { const updateItem = sessionUpdates.find((item) => item.old.id === row.id); return updateItem ? { ...row, status: updateItem.next, remarks: editing.remark, lastModified: changedAt, modifiedBy: "Admin" } : row; }));
    setPeriods({ ...periods, [editing.student.studentId]: editing.periods });
    setChanges([...changesToSave.map((change, index) => ({ ...change, id: `${Date.now()}-${index}`, studentId: editing.student.studentId, reason: editing.remark, changedAt, changedBy: "Admin" })), ...changes]); setEditing(null); say("Student attendance updated successfully.");
  };
  const action = <div className="att-filter-action"><button className="cms-btn cms-btn-primary" onClick={() => setLoaded(true)}>{filters.view === "Monthly Report" ? "Apply Filters" : "Load Records"}</button>{filters.view === "Monthly Report" ? <button className="cms-btn cms-btn-ghost" onClick={() => say("Monthly report export is ready for download.")}>Export</button> : null}</div>;
  return <><section className="att-card att-filter-card"><div className="att-filter-grid att-student-filter-grid">{filters.view === "Monthly Report" ? <Field label="Month"><div className="att-month-picker"><span>{monthLabel}</span><CalendarDays size={18} aria-hidden="true" /><input type="month" value={filters.date.slice(0, 7)} aria-label="Month" onChange={(event) => setFilters({ ...filters, date: `${event.target.value}-01` })} /></div></Field> : <Field label="Date"><input type="date" value={filters.date} onChange={update("date")} /></Field>}<Select label="Board" value={filters.board} onChange={update("board")} items={mockBoards} all="All Boards" /><Select label="Academic Year" value={filters.year} onChange={update("year")} items={mockAcademicYears} all="All Academic Years" /><Select label="Academic Level" value={filters.level} onChange={update("level")} items={mockAcademicLevels} all="All Academic Levels" /><Select label="Group" value={filters.group} onChange={update("group")} items={mockGroups} all="All Groups" /><Select label="Section" value={filters.section} onChange={update("section")} items={mockSections} all="All Sections" /><Select label="Status" value={filters.status} onChange={update("status")} items={studentStatuses} all="All Status" /><Select label="View" value={filters.view} onChange={update("view")} items={studentViews} /></div>{action}</section>{loaded && <StudentView view={filters.view} students={students} date={filters.date} query={query} setQuery={setQuery} onEdit={(student) => setEditing({ student, sessions: [student.morning?.status || "Present", student.afternoon?.status || "Present"], periods: periodValues(student), remark: "" })} />}{editing && <StudentEditModal editing={editing} setEditing={setEditing} close={() => setEditing(null)} save={save} />}</>;
}

function StudentView({ view, students, date, query, setQuery, onEdit }) {
  if (view === "Monthly Report") return <CalendarReport rows={students.flatMap((student) => [student.morning, student.afternoon].filter(Boolean))} month={date} />;
  if (view === "Defaulters") return <StudentDefaulters rows={students} />;
  return <><section className="att-student-search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search student name, roll no. or admission no." /></section><StudentSummary rows={students} /><StudentSessionTable rows={students} onEdit={onEdit} /></>;
}

function StudentSummary({ rows }) { const sessions = rows.flatMap((student) => [student.morning, student.afternoon].filter(Boolean)); return <section className="att-summary">{[["Total Students", rows.length], ["Present", sessions.filter((record) => record.status === "Present").length], ["Absent", sessions.filter((record) => record.status === "Absent").length], ["Leave", sessions.filter((record) => record.status === "Leave").length], ["Attendance %", `${pct(sessions)}%`]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</section>; }
function StudentSessionTable({ rows, onEdit }) { return <section className="att-card att-table-card"><div className="att-scroll"><table className="cms-table att-table att-student-attendance-table"><thead><tr><th>Student Name</th><th>Roll No</th><th>Admission No</th><th>Group</th><th>Section</th><th>Morning</th><th>Afternoon</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map((student) => { const status = (session) => student[session.toLowerCase()]?.status || "—"; return <tr key={student.studentId}><td>{student.studentName}</td><td>{student.rollNo}</td><td>{student.admissionNo}</td><td>MPC</td><td>MPC-A</td><td><Status value={status("Morning")} /></td><td><Status value={status("Afternoon")} /></td><td><button type="button" className="cms-action-btn" title="Edit Attendance" aria-label="Edit Attendance" onClick={() => onEdit(student)}><Pencil size={16} /></button></td></tr>; }) : <tr><td colSpan="8"><div className="cms-empty">No students match the selected filters.</div></td></tr>}</tbody></table></div></section>; }
function StudentDefaulters({ rows }) { const [threshold, setThreshold] = useState(75); const filtered = rows.filter((student) => pct([student.morning, student.afternoon].filter(Boolean)) < threshold); return <><section className="att-card att-person-filter"><Field label="Attendance Threshold"><input type="number" value={threshold} min="0" max="100" onChange={(event) => setThreshold(Number(event.target.value))} /></Field></section><section className="att-card att-table-card"><div className="att-scroll"><table className="cms-table"><thead><tr><th>Student Name</th><th>Roll No</th><th>Admission No</th><th>Group</th><th>Section</th><th>Attendance %</th><th>Shortage %</th></tr></thead><tbody>{filtered.length ? filtered.map((student) => { const score = pct([student.morning, student.afternoon].filter(Boolean)); return <tr key={student.studentId}><td>{student.studentName}</td><td>{student.rollNo}</td><td>{student.admissionNo}</td><td>MPC</td><td>MPC-A</td><td>{score}%</td><td>{100 - score}%</td></tr>; }) : <tr><td colSpan="7"><div className="cms-empty">No students are below this threshold.</div></td></tr>}</tbody></table></div></section></>; }
function Status({ value, compact }) { const short = value === "Leave" ? "LV" : value === "Present" ? "P" : value === "Absent" ? "A" : value; return <span className={`att-status ${compact ? "att-period-status" : ""}`}>{compact ? short : value}</span>; }
function StudentEditModal({ editing, setEditing, close, save }) { const sessions = [editing.student.morning, editing.student.afternoon].filter(Boolean); return <Modal title="Edit Student Attendance" onClose={close} footer={<><button className="cms-btn cms-btn-ghost" onClick={close}>Cancel</button><button className="cms-btn cms-btn-primary" onClick={save}>Save Changes</button></>}><div className="att-modal-fields att-student-attendance-modal"><p><b>{editing.student.studentName}</b></p><p>Roll No: {editing.student.rollNo} · Admission No: {editing.student.admissionNo} · Date: {editing.student.date}</p><p>Academic Year: 2026-2027 · Academic Level: Intermediate 1st Year · Group: MPC · Section: MPC-A</p><p>Last Modified: {sessions.map((record) => record.lastModified).find(Boolean) || "—"} · Modified By: {sessions.map((record) => record.modifiedBy).find(Boolean) || "—"}</p><p>Existing Remark: {sessions.map((record) => record.remarks).find(Boolean) || "—"}</p><div className="att-detail-history"><b>Session Attendance</b><div className="att-time-fields"><Select label="Morning" value={editing.sessions[0]} onChange={(event) => setEditing({ ...editing, sessions: [event.target.value, editing.sessions[1]] })} items={studentStatuses} /><Select label="Afternoon" value={editing.sessions[1]} onChange={(event) => setEditing({ ...editing, sessions: [editing.sessions[0], event.target.value] })} items={studentStatuses} /></div></div><div className="att-detail-history"><b>Period Attendance</b><div className="att-period-edit">{editing.periods.map((status, index) => <Select key={index} label={`P${index + 1} · Subject unavailable`} value={status} onChange={(event) => { const periods = [...editing.periods]; periods[index] = event.target.value; setEditing({ ...editing, periods }); }} items={studentStatuses} />)}</div></div><Field label="Reason / Remark"><textarea value={editing.remark} onChange={(event) => setEditing({ ...editing, remark: event.target.value })} /></Field></div></Modal>; }

function AttendanceScreen({ staff, records, setRecords, say }) {
  const views = staff ? staffViews : studentViews; const statuses = staff ? staffStatuses : studentStatuses;
  const [filters, setFilters] = useState({ date: "2026-09-02", board: "", year: "", level: "", group: "", section: "", session: "", type: "", department: "", person: "", status: "", view: "Attendance" });
 const [loaded, setLoaded] = useState(false); const [editing, setEditing] = useState(null); const [viewing, setViewing] = useState(null); const [changes, setChanges] = useState([]); const [openHistory, setOpenHistory] = useState("");
  const monthLabel = new Date(`${filters.date.slice(0, 7)}-01T00:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" }).replace(" ", ", ");
  const update = (key) => (e) => setFilters({ ...filters, [key]: e.target.value });
  const rows = records.filter((r) => r.date === filters.date && (!filters.status || r.status === filters.status) && (!staff ? (!filters.board || String(r.boardId) === filters.board) && (!filters.year || String(r.academicYearId) === filters.year) && (!filters.level || String(r.academicLevelId) === filters.level) && (!filters.group || String(r.groupId) === filters.group) && (!filters.section || String(r.sectionId) === filters.section) && (!filters.session || r.session === filters.session) : (!filters.type || r.staffType === filters.type) && (!filters.department || r.department === filters.department) && (!filters.person || r.staffId === filters.person)));
  const save = () => {
    const prior = records.find((r) => r.id === editing.id); const changedAt = time();
    if ((!staff || prior.status !== editing.status) && !editing.remark?.trim()) return say("Reason / remark is required when attendance status changes.");
    setRecords(records.map((r) => r.id === editing.id ? { ...editing, remarks: editing.remark, lastModified: changedAt, modifiedBy: "Admin" } : r));
    setChanges([{ id: Date.now(), recordId: editing.id, oldStatus: prior.status, newStatus: editing.status, reason: editing.remark, changedAt, changedBy: "Admin" }, ...changes]); setEditing(null); say(`${staff ? "Staff" : "Student"} attendance updated successfully.`);
  };
  return <>
    <section className="att-card att-filter-card"><div className={`att-filter-grid ${staff ? "att-staff-filter-grid" : "att-student-filter-grid"}`}>
      {staff && filters.view === "Monthly Report" ? <Field label="Month"><div className="att-month-picker"><span>{monthLabel}</span><CalendarDays size={18} aria-hidden="true" /><input type="month" value={filters.date.slice(0, 7)} aria-label="Month" onChange={(event) => setFilters({ ...filters, date: `${event.target.value}-01` })} /></div></Field> : <Field label="Date"><input type="date" value={filters.date} onChange={update("date")} /></Field>}
      {staff ? <><Select label="Academic Year" value={filters.year} onChange={update("year")} items={mockAcademicYears} all="All Academic Years" /><Select label="Staff Type" value={filters.type} onChange={update("type")} items={["Teaching Staff", "Non-Teaching Staff"]} all="All Staff" /><Select label="Department" value={filters.department} onChange={update("department")} items={[...new Set(records.map((r) => r.department))]} all="All Departments" /><Select label="Staff" value={filters.person} onChange={update("person")} items={records.map((r) => ({ id: r.staffId, name: `${r.staffName} (${r.staffId})` }))} all="All Staff" /></> : <><Select label="Board" value={filters.board} onChange={update("board")} items={mockBoards} all="All Boards" /><Select label="Academic Year" value={filters.year} onChange={update("year")} items={mockAcademicYears} all="All Academic Years" /><Select label="Academic Level" value={filters.level} onChange={update("level")} items={mockAcademicLevels} all="All Academic Levels" /><Select label="Group" value={filters.group} onChange={update("group")} items={mockGroups} all="All Groups" /><Select label="Section" value={filters.section} onChange={update("section")} items={mockSections} all="All Sections" /><Select label="Session" value={filters.session} onChange={update("session")} items={["Morning", "Afternoon"]} all="All Sessions" /></>}
      <Select label="Status" value={filters.status} onChange={update("status")} items={statuses} all="All Status" /><Select label="View" value={filters.view} onChange={update("view")} items={views} />
    </div><div className="att-filter-action"><button className="cms-btn cms-btn-primary" onClick={() => setLoaded(true)}>{!staff && filters.view === "Monthly Report" ? "Apply Filters" : "Load Records"}</button>{!staff && filters.view === "Monthly Report" ? <button className="cms-btn cms-btn-ghost" onClick={() => say("Monthly report export is ready for download.")}>Export</button> : null}</div></section>
    {loaded && <Content staff={staff} view={filters.view} rows={rows} allRecords={records} month={filters.date} onEdit={setEditing} onView={setViewing} changes={changes} openHistory={openHistory} setOpenHistory={setOpenHistory} />}
    {editing && <EditModal record={editing} student={!staff} statuses={statuses} setRecord={setEditing} close={() => setEditing(null)} save={save} />}
    {viewing && <AttendanceDetailsModal record={viewing} student={!staff} changes={changes.filter((change) => change.recordId === viewing.id)} close={() => setViewing(null)} />}
  </>;
}

function Summary({ rows, staff }) { const labels = staff ?  ["Total Staff", "Present", "Absent", "Leave", "Late"] : ["Total Students", "Present", "Absent", "Leave", "Attendance %"]; return <section className="att-summary">{labels.map((label) => <div key={label}><span>{label}</span><b>{label === "Attendance %" ? `${pct(rows)}%` : label.startsWith("Total") ? rows.length : rows.filter((r) => r.status === label).length}</b></div>)}</section>; }
function Content({ staff, view, rows, allRecords, month, onEdit, onView, changes, openHistory, setOpenHistory }) {
  if (view === "Monthly Report") return <CalendarReport rows={staff ? allRecords : rows} month={month} staff={staff} />;
  if (!staff && view === "Student-wise Report") return <PersonReport rows={allRecords} staff={staff} />;
  if (view === "Session-wise Report") return <SessionReport rows={rows} />;
  if (!staff && view === "Defaulters") return <Defaulters rows={allRecords} staff={staff} />;
  return <><Summary rows={rows} staff={staff} /><AttendanceTable rows={rows} staff={staff} onEdit={view === "Attendance" ? onEdit : null} changes={changes} openHistory={openHistory} setOpenHistory={setOpenHistory} /></>;
}
function AttendanceTable({ rows, staff, onEdit, changes = [], openHistory, setOpenHistory }) { const [search, setSearch] = useState(""); const visibleRows = staff ? rows.filter((record) => `${record.staffName} ${record.staffId}`.toLowerCase().includes(search.trim().toLowerCase())) : rows; return <section className="att-card att-table-card"><div className="att-table-top">{staff ? <label className="att-table-search"><span>Search Staff</span><input className="att-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by staff name or staff ID" /></label> : <b>Student Attendance</b>}</div><div className="att-scroll"><table className="cms-table att-table"><thead><tr>{staff ? <><th>Staff ID</th><th>Staff Name</th><th>Department</th><th>Staff Type</th></> : <><th>Student Name</th><th>Roll No</th><th>Admission No</th><th>Group</th><th>Section</th><th>Session</th></>}<th>Status</th>{staff && <><th>In Time</th><th>Out Time</th></>}<th>Action</th></tr></thead><tbody>{visibleRows.length ? visibleRows.map((r) => <RecordRow key={r.id} r={r} staff={staff} onEdit={onEdit} changes={changes.filter((c) => c.recordId === r.id)} open={openHistory === r.id} toggle={() => setOpenHistory?.(openHistory === r.id ? "" : r.id)} />) : <tr><td colSpan="12"><div className="cms-empty">{search ? "No loaded staff attendance records match this search." : "No attendance records match the selected filters."}</div></td></tr>}</tbody></table></div></section>; }
function RecordRow({ r, staff, onEdit, changes, open, toggle }) { return <>{<tr>{staff ? <><td>{r.staffId}</td><td>{r.staffName}</td><td>{r.department}</td><td>{r.staffType}</td></> : <><td>{r.studentName}</td><td>{r.rollNo}</td><td>{r.admissionNo}</td><td>MPC</td><td>MPC-A</td><td>{r.session}</td></>}<td><span className="att-status">{r.status}</span></td>{staff && <><td>{r.inTime}</td><td>{r.outTime}</td></>}<td>{onEdit ? <button type="button" className="cms-action-btn" title="Edit Attendance" aria-label="Edit Attendance" onClick={() => onEdit({ ...r, remark: r.remarks || "" })}><Pencil size={16} /></button> : "—"}</td></tr>}{changes.length ? <tr className="att-history-row"><td colSpan="12"><button type="button" className="att-history-toggle" onClick={toggle}>Change History {open ? "▴" : "▾"}</button>{open && changes.map((c) => <div key={c.id}>{c.oldStatus} → {c.newStatus} · Changed By: {c.changedBy} · Reason: {c.reason} · Changed At: {c.changedAt}</div>)}</td></tr> : null}</>; }
function EditModal({ record, student, statuses, setRecord, close, save }) { return <Modal title={student ? "Edit Student Attendance" : "Edit Staff Attendance"} onClose={close} footer={<><button className="cms-btn cms-btn-ghost" onClick={close}>Cancel</button><button className="cms-btn cms-btn-primary" onClick={save}>Save Changes</button></>}><div className="att-modal-fields"><p><b>{record.studentName || record.staffName}</b></p>{student ? <p>{`Roll No: ${record.rollNo} · Date: ${record.date} · ${record.session}`}</p> : <><p>Staff ID: {record.staffId} · Date: {record.date}</p><p>Department: {record.department} · Staff Type: {record.staffType}</p></>}<Field label="Current Status"><input value={record.status} disabled /></Field><Select label="New Status" value={record.status} onChange={(e) => setRecord({ ...record, status: e.target.value })} items={statuses} />{!student && <div className="att-time-fields"><Field label="In Time"><input value={record.inTime} onChange={(e) => setRecord({ ...record, inTime: e.target.value })} /></Field><Field label="Out Time"><input value={record.outTime} onChange={(e) => setRecord({ ...record, outTime: e.target.value })} /></Field></div>}<Field label="Reason / Remark"><textarea value={record.remark} onChange={(e) => setRecord({ ...record, remark: e.target.value })} /></Field></div></Modal>; }
function AttendanceDetailsModal({ record, student, changes, close }) { return <Modal title={student ? "Student Attendance Details" : "Staff Attendance Details"} onClose={close} footer={<button className="cms-btn cms-btn-primary" onClick={close}>Close</button>}><div className="att-modal-fields"><p><b>{record.studentName || record.staffName}</b></p>{student ? <><p>Roll No: {record.rollNo}</p><p>Admission No: {record.admissionNo}</p><p>Date: {record.date} · Session: {record.session}</p><p>Group: MPC · Section: MPC-A</p></> : <><p>Staff ID: {record.staffId}</p><p>{record.department} · {record.staffType}</p><p>Date: {record.date}</p><p>In Time: {record.inTime} · Out Time: {record.outTime}</p><p>Verification: {record.verificationMethod || "Manual"}</p></>}<p>Current Status: <b>{record.status}</b></p><p>Last Modified: {record.lastModified || record.date}</p><p>Modified By: {record.modifiedBy || "Faculty"}</p><p>Remark: {record.remarks || "—"}</p>{changes.length ? <div className="att-detail-history"><b>Change History</b>{changes.map((change) => <p key={change.id}>{change.oldStatus} → {change.newStatus} · {change.changedBy} · {change.reason} · {change.changedAt}</p>)}</div> : null}</div></Modal>; }
function ReportTable({ headers, rows }) { return <section className="att-card att-table-card"><div className="att-scroll"><table className="cms-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((v, j) => <td key={j}>{v}</td>)}</tr>)}</tbody></table></div></section>; }
function people(rows, staff) { return Object.values(rows.reduce((a, r) => { const key = staff ? r.staffId : r.studentId; (a[key] ||= { name: r.staffName || r.studentName, rows: [] }).rows.push(r); return a; }, {})); }
function Monthly({ rows, staff }) { return <ReportTable headers={[staff ? "Staff" : "Student", "Present", "Absent", "Leave", ...(staff ? ["Late", "Working Days"] : ["Total Sessions"]), "Attendance %"]} rows={people(rows, staff).map((p) => [p.name, ...studentStatuses.map((s) => p.rows.filter((r) => r.status === s).length), ...(staff ? [p.rows.filter((r) => r.status === "Late").length, p.rows.length] : [p.rows.length]), `${pct(p.rows)}%`])} />; }
function MonthlyCalendar({ rows, month }) {
  const start = new Date(`${month.slice(0, 7)}-01T00:00:00`); const year = start.getFullYear(); const monthIndex = start.getMonth(); const days = Array.from({ length: new Date(year, monthIndex + 1, 0).getDate() }, (_, i) => new Date(year, monthIndex, i + 1));
  const students = Object.values(rows.reduce((all, row) => { (all[row.studentId] ||= { ...row, sessions: [] }).sessions.push(row); return all; }, {}));
  const label = start.toLocaleDateString("en-IN", { month: "long", year: "numeric" });
  const statusFor = (student, day) => {
    if (day.getDay() === 0) return "-";
    const date = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, "0")}-${String(day.getDate()).padStart(2, "0")}`; const existing = student.sessions.find((row) => row.date === date);
    if (existing) return existing.status === "Leave" ? "LV" : existing.status.charAt(0);
    const seed = Number(student.rollNo) + day.getDate(); return seed % 13 === 0 ? "LV" : seed % 7 === 0 ? "A" : "P";
  };
  return <section className="att-card att-month-card"><header className="att-month-header"><div><h3>Monthly Attendance</h3><p>{label} • {days.length} days</p></div><div className="att-month-legend"><span><i className="is-present">P</i> Present</span><span><i className="is-absent">A</i> Absent</span><span><i className="is-leave">LV</i> Leave</span><span><i className="is-off">−</i> Non-working day</span></div></header><div className="att-month-scroll"><table className="cms-table att-month-table"><thead><tr><th className="att-sticky-roll">Roll No</th><th className="att-sticky-name">Student Name</th><th>Group</th><th>Section</th>{days.map((day) => <th key={day.toISOString()} className={day.getDay() === 0 ? "is-sunday" : ""}><b>{day.getDate()}</b><small>{day.toLocaleDateString("en-US", { weekday: "short" }).toUpperCase()}</small></th>)}</tr></thead><tbody>{students.length ? students.map((student) => <tr key={student.studentId}><td className="att-sticky-roll">{student.rollNo}</td><td className="att-sticky-name">{student.studentName}</td><td>MPC</td><td>MPC-A</td>{days.map((day) => { const status = statusFor(student, day); return <td key={day.toISOString()} className={status === "-" ? "is-sunday" : ""}><span className={`att-month-status att-month-${status.toLowerCase().replace("-", "off")}`}>{status}</span></td>; })}</tr>) : <tr><td colSpan={days.length + 4}><div className="cms-empty">No students match the selected filters.</div></td></tr>}</tbody></table></div></section>;
}
function CalendarReport({ rows, month, staff = false }) {
  const start = new Date(`${month.slice(0, 7)}-01T00:00:00`); const days = Array.from({ length: new Date(start.getFullYear(), start.getMonth() + 1, 0).getDate() }, (_, i) => new Date(start.getFullYear(), start.getMonth(), i + 1));
  const people = Object.values(rows.reduce((all, row) => { const id = staff ? row.staffId : row.studentId; (all[id] ||= { ...row, records: [] }).records.push(row); return all; }, {}));
  const value = (person, day) => { if (day.getDay() === 0) return "-"; const key = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, "0")}-${String(day.getDate()).padStart(2, "0")}`; const existing = person.records.find((record) => record.date === key); if (existing) return existing.status === "Leave" ? "LV" : existing.status === "Late" ? "L" : existing.status.charAt(0); const seed = (Number(person.rollNo) || person.staffId.length) + day.getDate(); return staff && seed % 11 === 0 ? "L" : seed % 13 === 0 ? "LV" : seed % 7 === 0 ? "A" : "P"; };
  const label = start.toLocaleDateString("en-IN", { month: "long", year: "numeric" });
  return <section className="att-card att-month-card"><header className="att-month-header"><div><h3>Monthly Attendance</h3><p>{label} • {days.length} days</p></div><div className="att-month-legend"><span><i className="is-present">P</i> Present</span><span><i className="is-absent">A</i> Absent</span><span><i className="is-leave">LV</i> Leave</span>{staff ? <span><i className="is-late">L</i> Late</span> : null}<span><i className="is-off">−</i> Non-working day</span></div></header><div className="att-month-scroll"><table className="cms-table att-month-table"><thead><tr><th className="att-sticky-roll">{staff ? "Staff ID" : "Roll No"}</th><th className="att-sticky-name">{staff ? "Staff Name" : "Student Name"}</th>{days.map((day) => <th key={day.toISOString()}><b>{day.getDate()}</b><small>{day.toLocaleDateString("en-US", { weekday: "short" }).toUpperCase()}</small></th>)}<th>Present</th><th>Absent</th><th>Leave</th>{staff ? <><th>Late</th><th>Working Days</th></> : null}<th>Attendance %</th></tr></thead><tbody>{people.map((person) => { const values = days.map((day) => value(person, day)).filter((status) => status !== "-"); const count = (status) => values.filter((item) => item === status).length; return <tr key={staff ? person.staffId : person.studentId}><td className="att-sticky-roll">{staff ? person.staffId : person.rollNo}</td><td className="att-sticky-name">{staff ? person.staffName : person.studentName}</td>{days.map((day) => { const status = value(person, day); return <td key={day.toISOString()}><span className={`att-month-status att-month-${status.toLowerCase().replace("-", "off")}`}>{status}</span></td>; })}<td>{count("P")}</td><td>{count("A")}</td><td>{count("LV")}</td>{staff ? <><td>{count("L")}</td><td>{values.length}</td></> : null}<td>{values.length ? Math.round(count("P") * 100 / values.length) : 0}%</td></tr>; })}</tbody></table></div></section>;
}
function PersonReport({ rows, staff }) {
  const all = people(rows, staff);
  const [name, setName] = useState(all[0]?.name || "");
  const [query, setQuery] = useState("");
  const chosen = all.find((p) => p.name === name) || { rows: [] };
  if (staff) { const staffMembers = all.map((person) => ({ ...person, staff: person.rows[0] })); const matches = staffMembers.filter(({ staff: member }) => `${member.staffName} ${member.staffId}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8); const profile = chosen.rows[0]; return <><section className="att-card att-person-filter"><div className="att-admission-search"><Field label="Search Staff"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search staff name or staff ID" /></Field>{query ? <div className="att-admission-results" role="listbox">{matches.length ? matches.map(({ name: staffName, staff: member }) => <button key={member.staffId} type="button" onClick={() => { setName(staffName); setQuery(""); }}><strong>{member.staffName}</strong><span>{member.staffId} · {member.department} · {member.staffType}</span></button>) : <div className="att-admission-empty">No staff members found.</div>}</div> : null}</div></section>{profile ? <section className="att-card att-person-profile"><b>{profile.staffName}</b><span>{profile.staffId} · {profile.department} · {profile.staffType}</span></section> : null}<Summary rows={chosen.rows} staff /><ReportTable headers={["Date", "Status", "In Time", "Out Time", "Verification Method", "Remark"]} rows={chosen.rows.map((r) => [r.date, r.status, r.inTime, r.outTime, r.verificationMethod || "Manual", r.remarks || "—"])} /></>; }
  const admissions = all.map((person) => ({ ...person, student: person.rows[0] }));
  const matches = admissions.filter(({ student }) => `${student.studentName} ${student.rollNo} ${student.admissionNo}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8);
  return <><section className="att-card att-person-filter"><div className="att-admission-search"><Field label="Search Student"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student name, roll no. or admission no." /></Field>{query ? <div className="att-admission-results" role="listbox">{matches.length ? matches.map(({ name: studentName, student }) => <button key={student.studentId} type="button" onClick={() => { setName(studentName); setQuery(""); }}><strong>{student.studentName}</strong><span>Roll No. {student.rollNo} · {student.admissionNo}</span></button>) : <div className="att-admission-empty">No admissions found.</div>}</div> : null}</div></section><Summary rows={chosen.rows} /><ReportTable headers={["Date", "Session", "Status", "Modified By"]} rows={chosen.rows.map((r) => [r.date, r.session, r.status, r.modifiedBy || "Faculty"])} /></>;
}
function SessionReport({ rows }) { return <ReportTable headers={["Session", "Present", "Absent", "Leave", "Attendance %"]} rows={["Morning", "Afternoon"].map((s) => { const data = rows.filter((r) => r.session === s); return [s, ...studentStatuses.map((x) => data.filter((r) => r.status === x).length), `${pct(data)}%`]; })} />; }
function DepartmentReport({ rows }) { return <ReportTable headers={["Department", "Staff", "Present", "Absent", "Leave", "Late", "Attendance %"]} rows={[...new Set(rows.map((r) => r.department))].map((d) => { const data = rows.filter((r) => r.department === d); return [d, data.length, ...staffStatuses.map((s) => data.filter((r) => r.status === s).length), `${pct(data)}%`]; })} />; }
function Defaulters({ rows, staff }) { const [threshold, setThreshold] = useState(75); const data = people(rows, staff).filter((p) => pct(p.rows) < threshold); const staffRows = data.map((person) => { const member = person.rows[0]; const attendance = pct(person.rows); return [member.staffId, member.staffName, member.department, member.staffType, `${attendance}%`, `${Math.max(0, threshold - attendance)}%`]; }); return <><section className="att-card att-person-filter"><Field label="Attendance Percentage Threshold"><input type="number" min="0" max="100" value={threshold} onChange={(e) => setThreshold(Number(e.target.value))} /></Field></section><ReportTable headers={staff ? ["Staff ID", "Staff Name", "Department", "Staff Type", "Attendance %", "Shortage"] : ["Student", "Present", "Absent", "Leave", "Attendance %"]} rows={staff ? staffRows : data.map((p) => [p.name, ...studentStatuses.map((s) => p.rows.filter((r) => r.status === s).length), `${pct(p.rows)}%`])} /></>; }
