import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { CalendarDays, Pencil } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import { Loader, Modal, Toast } from "@/components/common/Ui.jsx";
import apiClient, { getApiErrorMessage } from "@/api/apiClient.js";
import { apiEndpoints } from "@/api/apiEndpoints.js";
import { useAcademicContext } from "@/context/AcademicContext.jsx";
import "./AttendancePage.css";

const STUDENT_STATUSES = ["Present", "Absent", "Leave"], STAFF_STATUSES = [...STUDENT_STATUSES, "Late"];
const LABEL = { 1: "Present", 2: "Absent", 3: "Late", 4: "Leave" }, VALUE = { Present: 1, Absent: 2, Late: 3, Leave: 4 };
const asList = (v) => Array.isArray(v) ? v : Array.isArray(v?.items) ? v.items : Array.isArray(v?.records) ? v.records : Array.isArray(v?.data) ? v.data : [];
const body = (r) => r?.data?.data ?? r?.data ?? r ?? {};
const get = (o, ...keys) => keys.map((k) => o?.[k]).find((v) => v !== undefined && v !== null);
const num = (v) => v === "" || v == null ? undefined : Number(v);
const status = (v) => LABEL[v] ?? v ?? "—";
const staffType = (v) => v === "" || v == null ? undefined : String(v) === "1" || /non/i.test(v) ? 1 : 0;
const Field = ({ label, children }) => <label className="att-field"><span>{label}</span>{children}</label>;
function Select({ label, value, onChange, items = [], all, disabled = false }) { return <Field label={label}><select value={value} onChange={onChange} disabled={disabled}>{all ? <option value="">{all}</option> : null}{items.map((x) => { const id = get(x, "id", "Id", "sectionId", "programId", "groupId", "academicLevelId", "departmentId", "facultyId", "staffId", "academicYearId", "boardId") ?? x, name = get(x, "name", "Name", "sectionName", "programName", "programmeName", "groupName", "levelName", "departmentName", "staffName", "facultyName", "academicYearName", "boardName") ?? x; return <option key={String(id)} value={id}>{name}</option>; })}</select></Field>; }

export default function AttendancePage() { const { area = "student" } = useParams(), staff = area === "staff"; const [notice, setNotice] = useState({ message: "", type: "success" }); const say = (message, type = "success") => setNotice({ message, type }); return <><DashboardLayout title={staff ? "Staff Attendance" : "Student Attendance"} subtitle={staff ? "View and manage teaching and non-teaching staff attendance" : "View and manage student attendance records"} breadcrumb={["Operations", "Attendance"]}><main className="attendance-module">{staff ? <Screen staff say={say} /> : <Screen say={say} />}</main></DashboardLayout><Toast message={notice.message} type={notice.type} onClose={() => setNotice({ message: "", type: "success" })} /></>; }

function useOptions(staff) { const [o, setO] = useState({}); useEffect(() => { if (!staff) return undefined; let mounted = true; const calls = [apiEndpoints.departments.getAll, apiEndpoints.faculty.list]; Promise.allSettled(calls.map((url) => apiClient.get(url))).then((rs) => { if (!mounted) return; const values = rs.map((r) => r.status === "fulfilled" ? asList(body(r.value)) : []); setO({ departments: values[0], faculty: values[1] }); }); return () => { mounted = false; }; }, [staff]); return o; }

function useStudentOptions(boardId, academicYearId, levelId, groupId, programId) {
  const [options, setOptions] = useState({ levels: [], groups: [], programs: [], sections: [], loadingLevels: false, loadingGroups: false, loadingPrograms: false, loadingSections: false });
  useEffect(() => { if (!boardId) return; let active = true; setOptions((value) => ({ ...value, levels: [], loadingLevels: true })); apiClient.get(apiEndpoints.boards.academicLevels, { params: { boardId } }).then((response) => active && setOptions((value) => ({ ...value, levels: asList(body(response)), loadingLevels: false }))).catch(() => active && setOptions((value) => ({ ...value, levels: [], loadingLevels: false }))); return () => { active = false; }; }, [boardId]);
  useEffect(() => { if (!boardId || !levelId) { setOptions((value) => ({ ...value, groups: [], programs: [], sections: [], loadingGroups: false })); return undefined; } let active = true; setOptions((value) => ({ ...value, groups: [], programs: [], sections: [], loadingGroups: true })); apiClient.get(apiEndpoints.groups.getByBoard(boardId), { params: { academicYearId, academicLevelId: levelId, isActive: true } }).then((response) => { if (!active) return; const payload = body(response); const wrappers = asList(payload); const groupRows = Array.isArray(payload?.groups) ? payload.groups : Array.isArray(payload?.Groups) ? payload.Groups : wrappers.flatMap((item) => Array.isArray(item?.groups) ? item.groups : Array.isArray(item?.Groups) ? item.Groups : Array.isArray(item?.groupList) ? item.groupList : Array.isArray(item?.data) ? item.data : get(item, "groupId", "GroupId", "id", "Id") != null ? [item] : []); setOptions((value) => ({ ...value, groups: groupRows.filter((item) => get(item, "groupId", "GroupId", "id", "Id") != null && item?.isActive !== false && item?.IsActive !== false), loadingGroups: false })); }).catch(() => active && setOptions((value) => ({ ...value, groups: [], loadingGroups: false }))); return () => { active = false; }; }, [boardId, academicYearId, levelId]);
  useEffect(() => { if (!groupId) { setOptions((value) => ({ ...value, programs: [], sections: [], loadingPrograms: false })); return undefined; } let active = true; setOptions((value) => ({ ...value, programs: [], sections: [], loadingPrograms: true })); apiClient.get(apiEndpoints.groups.programs(groupId)).then((response) => active && setOptions((value) => ({ ...value, programs: asList(body(response)), loadingPrograms: false }))).catch(() => active && setOptions((value) => ({ ...value, programs: [], loadingPrograms: false }))); return () => { active = false; }; }, [groupId]);
  useEffect(() => { if (!programId) { setOptions((value) => ({ ...value, sections: [], loadingSections: false })); return undefined; } let active = true; setOptions((value) => ({ ...value, sections: [], loadingSections: true })); apiClient.get(apiEndpoints.sections.list, { params: { boardId, academicYearId, academicLevelId: levelId, groupId, programId, ProgramId: programId, isActive: true, IsActive: true } }).then((response) => active && setOptions((value) => ({ ...value, sections: asList(body(response)), loadingSections: false }))).catch(() => active && setOptions((value) => ({ ...value, sections: [], loadingSections: false }))); return () => { active = false; }; }, [boardId, academicYearId, levelId, groupId, programId]);
  return options;
}

function Screen({ staff = false, say }) {
 const { selectedBoardId: navbarBoardId, selectedAcademicYearId: navbarAcademicYearId } = useAcademicContext(); const [f, setF] = useState({ date: "2026-09-02", level: "", group: "", section: "", program: "", department: "", type: "", person: "", status: "", view: "Attendance" }), [rows, setRows] = useState([]), [report, setReport] = useState(null), [loaded, setLoaded] = useState(false), [busy, setBusy] = useState(false), [editing, setEditing] = useState(null), [search, setSearch] = useState(""); const staffOptions = useOptions(staff), studentOptions = useStudentOptions(staff ? "" : navbarBoardId, navbarAcademicYearId, f.level, f.group, f.program); const options = staff ? staffOptions : studentOptions;
 const update = (key) => (e) => setF((old) => ({ ...old, [key]: e.target.value, ...(key === "level" ? { group: "", program: "", section: "" } : {}), ...(key === "group" ? { program: "", section: "" } : {}), ...(key === "program" ? { section: "" } : {}) }));
 useEffect(() => { if (!staff) setF((old) => ({ ...old, level: "", group: "", program: "", section: "" })); }, [staff, navbarBoardId, navbarAcademicYearId]);
 const monthParams = () => { const [year, month] = f.date.slice(0, 7).split("-"); return staff ? { month: Number(month), year: Number(year), academicYearId: num(navbarAcademicYearId), departmentId: num(f.department), staffType: staffType(f.type), ...(f.person ? { facultyId: num(f.person) } : {}) } : { month: Number(month), year: Number(year), boardId: num(navbarBoardId), academicYearId: num(navbarAcademicYearId), academicLevelId: num(f.level), groupId: num(f.group), sectionId: num(f.section), ...(f.program ? { programId: num(f.program) } : {}) }; };
 const load = async () => { setBusy(true); try { if (f.view === "Monthly Report") { const r = await apiClient.get(staff ? apiEndpoints.staffAttendance.monthlyReport : apiEndpoints.attendance.studentMonthlyReport, { params: monthParams() }); setReport(body(r)); } else if (!staff && f.view === "Defaulters") { const r = await apiClient.get(apiEndpoints.attendance.studentDefaulters, { params: { ...monthParams(), threshold: 75 } }); setRows(asList(body(r))); } else if (staff) { const r = await apiClient.post(apiEndpoints.staffAttendance.load, { date: f.date, academicYearId: num(navbarAcademicYearId), departmentId: num(f.department), staffType: staffType(f.type), ...(f.status ? { status: VALUE[f.status] } : {}), ...(f.person ? { facultyId: num(f.person) } : {}) }); setRows(asList(body(r))); } else { const r = await apiClient.get(apiEndpoints.attendance.studentAdminDaily, { params: { date: f.date, boardId: num(navbarBoardId), academicYearId: num(navbarAcademicYearId), academicLevelId: num(f.level), groupId: num(f.group), sectionId: num(f.section), ...(f.program ? { programId: num(f.program) } : {}) } }); setRows(asList(body(r))); } setLoaded(true); } catch (e) { say(getApiErrorMessage(e) || `Failed to load ${staff ? "staff" : "student"} attendance.`, "error"); } finally { setBusy(false); } };
 const save = async () => { const r = editing.record; const changed = staff ? editing.status !== status(r.status) : editing.morning !== status(r.morningStatus) || editing.afternoon !== status(r.afternoonStatus); if (!changed) return setEditing(null); if (!editing.remarks.trim()) return say("Reason / remark is required when attendance changes.", "error"); setBusy(true); try { if (staff) await apiClient.put(apiEndpoints.staffAttendance.update, { facultyId: get(r, "facultyId", "staffId", "id"), attendanceDate: f.date, departmentId: num(f.department) ?? get(r, "departmentId"), staffType: staffType(f.type) ?? get(r, "staffType"), status: VALUE[editing.status], inTime: editing.inTime || null, outTime: editing.outTime || null, remarks: editing.remarks }); else await apiClient.put(apiEndpoints.attendance.studentUpdate, { studentId: get(r, "studentId", "id"), attendanceDate: f.date, morningStatus: editing.morning !== status(r.morningStatus) ? VALUE[editing.morning] : null, afternoonStatus: editing.afternoon !== status(r.afternoonStatus) ? VALUE[editing.afternoon] : null, boardId: num(navbarBoardId), academicYearId: num(navbarAcademicYearId), academicLevelId: num(f.level), groupId: num(f.group), sectionId: num(f.section), ...(f.program ? { programId: num(f.program) } : {}), remarks: editing.remarks }); setEditing(null); say(`${staff ? "Staff" : "Student"} attendance updated successfully.`); await load(); } catch (e) { say(getApiErrorMessage(e) || "Failed to update attendance.", "error"); } finally { setBusy(false); } };
 const exportReport = async (kind) => { setBusy(true); try { const endpoint = staff ? kind === "csv" ? apiEndpoints.staffAttendance.monthlyExportCsv : apiEndpoints.staffAttendance.monthlyExport : kind === "csv" ? apiEndpoints.attendance.studentMonthlyExportCsv : apiEndpoints.attendance.studentMonthlyExportExcel; const r = await apiClient.get(endpoint, { params: monthParams(), responseType: "blob" }); const url = URL.createObjectURL(r.data), a = document.createElement("a"); a.href = url; a.download = `${staff ? "staff" : "student"}-attendance-${f.date.slice(0, 7)}.${kind === "csv" ? "csv" : "xlsx"}`; a.click(); URL.revokeObjectURL(url); } catch (e) { say(getApiErrorMessage(e) || "Failed to export monthly report.", "error"); } finally { setBusy(false); } };
 useEffect(() => { if (!staff && navbarBoardId && navbarAcademicYearId) { load(); } }, [navbarBoardId, navbarAcademicYearId, f.date, f.view, f.level, f.group, f.section, f.program]);
 const visible = rows.filter((r) => !staff || `${get(r, "staffName", "facultyName")} ${get(r, "facultyId", "staffId")}`.toLowerCase().includes(search.toLowerCase())).filter((r) => staff || !f.status || [status(r.morningStatus), status(r.afternoonStatus)].includes(f.status));
 return <><Filters f={f} update={update} o={options} staff={staff} busy={busy} load={load} exportReport={exportReport} />{busy && !loaded ? <Loader label="Loading attendance..." /> : null}{loaded && (f.view === "Monthly Report" ? <Monthly data={report} staff={staff} /> : !staff && f.view === "Defaulters" ? <Defaulters rows={rows} /> : <>{staff ? <StaffSummary rows={rows} /> : <StudentSummary rows={visible} />}<section className="att-card att-table-card">{staff ? <div className="att-table-top"><label className="att-table-search"><span>Search Staff</span><input className="att-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by staff name or staff ID" /></label></div> : <div className="att-student-search"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search student name, roll no. or admission no." /></div>}<DailyTable rows={visible} staff={staff} edit={(record) => setEditing(staff ? { record, status: status(record.status), inTime: get(record, "inTime") || "", outTime: get(record, "outTime") || "", remarks: get(record, "remarks", "remark") || "" } : { record, morning: status(record.morningStatus), afternoon: status(record.afternoonStatus), remarks: get(record, "remarks", "remark") || "" })} /></section></>) }{editing ? <Edit editing={editing} setEditing={setEditing} staff={staff} date={f.date} save={save} close={() => setEditing(null)} busy={busy} /> : null}</>;
}

function Filters({ f, update, o, staff, busy, load, exportReport }) { const isMonth = f.view === "Monthly Report", label = new Date(`${f.date.slice(0, 7)}-01T00:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" }).replace(" ", ", "); return <section className="att-card att-filter-card"><div className={`att-filter-grid ${staff ? "att-staff-filter-grid" : "att-student-filter-grid"}`}>{isMonth ? <Field label="Month"><div className="att-month-picker"><span>{label}</span><CalendarDays size={18} /><input type="month" value={f.date.slice(0, 7)} onChange={(e) => update("date")({ target: { value: `${e.target.value}-01` } })} /></div></Field> : <Field label="Date"><input type="date" value={f.date} onChange={update("date")} /></Field>}{staff ? <><Select label="Academic Year" value={f.year} onChange={update("year")} items={o.years} all="All Academic Years" /><Select label="Staff Type" value={f.type} onChange={update("type")} items={[{ id: "0", name: "Teaching Staff" }, { id: "1", name: "Non-Teaching Staff" }]} all="All Staff" /><Select label="Department" value={f.department} onChange={update("department")} items={o.departments} all="All Departments" /><Select label="Staff" value={f.person} onChange={update("person")} items={(o.faculty || []).map((x) => ({ id: get(x, "facultyId", "id"), name: `${get(x, "staffName", "name")} (${get(x, "facultyId", "id")})` }))} all="All Staff" /></> : <><Select label="Academic Level" value={f.level} onChange={update("level")} items={o.levels} all={o.loadingLevels ? "Loading academic levels..." : "Select Academic Level"} disabled={o.loadingLevels} /><Select label="Group" value={f.group} onChange={update("group")} items={o.groups} all={o.loadingGroups ? "Loading groups..." : "Select Group"} disabled={!f.level || o.loadingGroups} /><Select label="Program" value={f.program} onChange={update("program")} items={o.programs} all={o.loadingPrograms ? "Loading programs..." : "Select Program"} disabled={!f.group || o.loadingPrograms} /><Select label="Section" value={f.section} onChange={update("section")} items={o.sections} all={o.loadingSections ? "Loading sections..." : "Select Section"} disabled={!f.program || o.loadingSections} /></>}<Select label="Status" value={f.status} onChange={update("status")} items={staff ? STAFF_STATUSES : STUDENT_STATUSES} all="All Status" /><Select label="View" value={f.view} onChange={update("view")} items={staff ? ["Attendance", "Monthly Report"] : ["Attendance", "Monthly Report", "Defaulters"]} /></div><div className="att-filter-action"><button className="cms-btn cms-btn-primary" disabled={busy} onClick={load}>{busy ? "Loading..." : isMonth && !staff ? "Apply Filters" : "Load Records"}</button>{isMonth ? <><button className="cms-btn cms-btn-ghost" disabled={busy} onClick={() => exportReport("csv")}>Export CSV</button><button className="cms-btn cms-btn-ghost" disabled={busy} onClick={() => exportReport("excel")}>Export Excel</button></> : null}</div></section>; }

function StudentSummary({ rows }) { const s = rows.flatMap((r) => [r.morningStatus, r.afternoonStatus]).filter((x) => x != null).map(status), p = s.filter((x) => x === "Present").length; return <Summary data={[["Total Students", rows.length], ["Present", p], ["Absent", s.filter((x) => x === "Absent").length], ["Leave", s.filter((x) => x === "Leave").length], ["Attendance %", s.length ? `${Math.round(p * 100 / s.length)}%` : "0%"]]} />; }
function StaffSummary({ rows }) { return <Summary data={[["Total Staff", rows.length], ...STAFF_STATUSES.map((x) => [x, rows.filter((r) => status(r.status) === x).length])]} />; }
function Summary({ data }) { return <section className="att-summary">{data.map(([l, v]) => <div key={l}><span>{l}</span><b>{v}</b></div>)}</section>; }
function DailyTable({ rows, staff, edit }) { const roll = !staff && rows.some((r) => get(r, "rollNo", "rollNumber") != null), admission = !staff && rows.some((r) => get(r, "admissionNo", "admissionNumber") != null); return <div className="att-scroll"><table className="cms-table att-table"><thead><tr>{staff ? <><th>Staff ID</th><th>Staff Name</th><th>Department</th><th>Designation</th><th>Status</th><th>In Time</th><th>Out Time</th></> : <><th>Student Name</th>{roll ? <th>Roll No</th> : null}{admission ? <th>Admission No</th> : null}<th>Group</th><th>Section</th><th>Morning</th><th>Afternoon</th></>}<th>Action</th></tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={get(r, staff ? "facultyId" : "studentId", "id") ?? i}>{staff ? <><td>{get(r, "facultyId", "staffId")}</td><td>{get(r, "staffName", "facultyName")}</td><td>{get(r, "departmentName", "department") || "—"}</td><td>{get(r, "designationName", "staffTypeName") || "—"}</td><td><Pill value={status(r.status)} /></td><td>{get(r, "inTime") || "—"}</td><td>{get(r, "outTime") || "—"}</td></> : <><td>{get(r, "studentName", "name")}</td>{roll ? <td>{get(r, "rollNo", "rollNumber") || "—"}</td> : null}{admission ? <td>{get(r, "admissionNo", "admissionNumber") || "—"}</td> : null}<td>{get(r, "groupName") || "—"}</td><td>{get(r, "sectionName") || "—"}</td><td><Pill value={status(r.morningStatus)} /></td><td><Pill value={status(r.afternoonStatus)} /></td></>}<td><button className="cms-action-btn" title="Edit Attendance" aria-label="Edit Attendance" onClick={() => edit(r)}><Pencil size={16} /></button></td></tr>) : <tr><td colSpan="9"><div className="cms-empty">No attendance records match the selected filters.</div></td></tr>}</tbody></table></div>; }
function Pill({ value }) { return <span className={`att-status-pill ${value === "Present" ? "att-month-p" : value === "Absent" ? "att-month-a" : value === "Leave" ? "att-month-lv" : value === "Late" ? "att-month-l" : "att-month-off"}`}>{value}</span>; }
function Edit({ editing, setEditing, staff, date, save, close, busy }) { const r = editing.record; return <Modal title={`Edit ${staff ? "Staff" : "Student"} Attendance`} onClose={close} footer={<><button className="cms-btn cms-btn-ghost" disabled={busy} onClick={close}>Cancel</button><button className="cms-btn cms-btn-primary" disabled={busy} onClick={save}>{busy ? "Saving..." : "Save Changes"}</button></>}><div className="att-modal-fields"><p><b>{get(r, staff ? "staffName" : "studentName", "name")}</b></p><p>{staff ? `Staff ID: ${get(r, "facultyId", "staffId")}` : `Roll No: ${get(r, "rollNo", "rollNumber") || "—"} · Admission No: ${get(r, "admissionNo", "admissionNumber") || "—"}`} · Date: {date}</p><p>{staff ? `Department: ${get(r, "departmentName") || "—"} · Designation: ${get(r, "designationName") || "—"}` : `Group: ${get(r, "groupName") || "—"} · Section: ${get(r, "sectionName") || "—"}`}</p>{staff ? <><p>Current Status: {status(r.status)}</p><Select label="New Status" value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })} items={STAFF_STATUSES} /><div className="att-time-fields"><Field label="In Time"><input type="time" value={editing.inTime} onChange={(e) => setEditing({ ...editing, inTime: e.target.value })} /></Field><Field label="Out Time"><input type="time" value={editing.outTime} onChange={(e) => setEditing({ ...editing, outTime: e.target.value })} /></Field></div></> : <><div className="att-detail-history"><b>Session Attendance</b><div className="att-time-fields"><Select label="Morning" value={editing.morning} onChange={(e) => setEditing({ ...editing, morning: e.target.value })} items={STUDENT_STATUSES} /><Select label="Afternoon" value={editing.afternoon} onChange={(e) => setEditing({ ...editing, afternoon: e.target.value })} items={STUDENT_STATUSES} /></div></div><div className="att-detail-history"><b>Period Attendance</b><p>Period details are not returned by the attendance API.</p></div></>}<Field label="Reason / Remark"><textarea value={editing.remarks} onChange={(e) => setEditing({ ...editing, remarks: e.target.value })} /></Field></div></Modal>; }
function Monthly({ data, staff }) { const headers = data?.dayHeaders ?? data?.headers ?? [], rows = data?.studentRows ?? data?.staffRows ?? data?.rows ?? []; return <section className="att-card att-month-card"><header className="att-month-header"><div><h3>{staff ? "Staff" : "Student"} Monthly Attendance</h3><p>{headers.length} days</p></div><div className="att-month-legend">P = Present · A = Absent · L = Late · LV = Leave · H / - = Holiday or non-working day</div></header><div className="att-month-scroll"><table className="cms-table att-month-table"><thead><tr><th className="att-sticky-roll">{staff ? "Staff ID" : "Roll No"}</th><th className="att-sticky-name">{staff ? "Staff Name" : "Student Name"}</th>{headers.map((h, i) => <th key={i}><b>{new Date(`${get(h, "date") ?? h}T00:00:00`).getDate() || i + 1}</b></th>)}<th>Present</th><th>Absent</th><th>Leave</th>{staff ? <><th>Late</th><th>Working Days</th></> : null}<th>Attendance %</th></tr></thead><tbody>{rows.map((r, i) => <MonthRow key={get(r, staff ? "facultyId" : "studentId", "id") ?? i} r={r} headers={headers} staff={staff} />)}</tbody></table></div></section>; }
function MonthRow({ r, headers, staff }) { const ds = r.dailyStatus ?? r.statuses ?? [], p = r.present ?? ds.filter((x) => x === "P").length, a = r.absent ?? ds.filter((x) => x === "A").length, lv = r.leave ?? ds.filter((x) => x === "LV").length, l = r.late ?? ds.filter((x) => x === "L").length, work = r.workingDays ?? ds.filter((x) => !["-", "H"].includes(x)).length, pc = r.attendancePercentage ?? (work ? Math.round((p + (staff ? l : 0)) * 100 / work) : 0); return <tr><td className="att-sticky-roll">{staff ? get(r, "facultyId", "staffId") : get(r, "rollNo", "rollNumber") || "—"}</td><td className="att-sticky-name">{get(r, staff ? "staffName" : "studentName", "name")}</td>{headers.map((_, i) => <td key={i}><Pill value={ds[i] ?? "-"} /></td>)}<td>{p}</td><td>{a}</td><td>{lv}</td>{staff ? <><td>{l}</td><td>{work}</td></> : null}<td>{pc}%</td></tr>; }
function Defaulters({ rows }) { return <section className="att-card att-table-card"><div className="att-scroll"><table className="cms-table att-table"><thead><tr><th>Student Name</th><th>Roll No</th><th>Admission No</th><th>Group</th><th>Section</th><th>Attendance %</th></tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={get(r, "studentId", "id") ?? i}><td>{get(r, "studentName", "name")}</td><td>{get(r, "rollNo", "rollNumber") || "—"}</td><td>{get(r, "admissionNo", "admissionNumber") || "—"}</td><td>{get(r, "groupName") || "—"}</td><td>{get(r, "sectionName") || "—"}</td><td>{get(r, "attendancePercentage", "percentage") ?? "—"}%</td></tr>) : <tr><td colSpan="6"><div className="cms-empty">No students are below this threshold.</div></td></tr>}</tbody></table></div></section>; }
