import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import DashboardLayout from "../layout/DashboardLayout";
import "./MarksEntryPage.css";

const Check = () => <span aria-hidden="true">✓</span>;
const Cross = () => <span aria-hidden="true">×</span>;
const PAGE_SIZE = 5;
const STATUS_META = {
  DRAFT: ["DRAFT", "cms-status-submitted"], SUBMITTED: ["SUBMITTED", "cms-status-submitted"],
  VERIFIED: ["VERIFIED", "cms-status-verified"], APPROVED: ["APPROVED", "cms-status-approved"],
  REJECTED: ["REJECTED", "cms-status-rejected"],
};
const BOARDS = [{ boardId: 1, boardName: "AP State Board" }];
const YEARS = [{ academicYearId: 1, boardId: 1, academicYearName: "2026-27" }];
const LEVELS = [{ academicLevelId: 1, boardId: 1, academicYearId: 1, levelName: "1st Year" }];
const GROUPS = [{ groupId: 1, academicLevelId: 1, groupName: "MPC" }, { groupId: 2, academicLevelId: 1, groupName: "BiPC" }];
const PROGRAMS = [
  { programId: "REGULAR", programName: "Regular Academic", groupIds: [1, 2] },
  { programId: "JEE_MAIN", programName: "JEE Main", groupIds: [1] },
  { programId: "NEET", programName: "NEET", groupIds: [2] },
];
const SECTIONS = [
  { sectionId: 1, sectionName: "MPC-Regular-A", boardId: 1, academicYearId: 1, academicLevelId: 1, groupId: 1, programId: "REGULAR" },
  { sectionId: 2, sectionName: "MPC-JEE-A", boardId: 1, academicYearId: 1, academicLevelId: 1, groupId: 1, programId: "JEE_MAIN" },
  { sectionId: 3, sectionName: "BiPC-NEET-A", boardId: 1, academicYearId: 1, academicLevelId: 1, groupId: 2, programId: "NEET" },
];
const SUBJECTS = [
  [101, "ENG", "English", 1, "LANGUAGE", false], [102, "SAN", "Sanskrit", 1, "LANGUAGE", false],
  [103, "MATH-1A", "Mathematics IA", 1, "CORE", false], [104, "MATH-1B", "Mathematics IB", 1, "CORE", false],
  [105, "PHY", "Physics", 1, "CORE", true], [106, "CHE", "Chemistry", 1, "CORE", true],
  [201, "BOT", "Botany", 2, "CORE", true], [202, "ZOO", "Zoology", 2, "CORE", true],
  [203, "PHY", "Physics", 2, "CORE", true], [204, "CHE", "Chemistry", 2, "CORE", true],
  [205, "ENG", "English", 2, "LANGUAGE", false],
].map(([subjectId, subjectCode, subjectName, groupId, category, practical]) => ({ subjectId, subjectCode, subjectName, groupId, category, practical }));
const EXAMS = [
  [1, "EXM-REG-001", "Quarterly Examination", 1, "REGULAR", "Regular Academic", "Regular Academic Pattern", "Written", "SUBJECT_WISE", 600, 35, [101, 102, 103, 104, 105, 106], "COMPLETED"],
  [2, "EXM-JEE-001", "JEE Main Mock", 1, "JEE_MAIN", "JEE Main", "JEE Main Pattern", "Objective", "COMBINED", 300, 40, [103, 104, 105, 106], "COMPLETED"],
  [3, "EXM-NEET-001", "NEET Grand Test", 2, "NEET", "NEET", "NEET Pattern", "Objective", "COMBINED", 300, 40, [201, 202, 203, 204], "COMPLETED"],
  [4, "EXM-FUTURE", "Scheduled Future Examination", 1, "REGULAR", "Regular Academic", "Regular Academic Pattern", "Written", "SUBJECT_WISE", 600, 35, [101, 102, 103, 104, 105, 106], "SCHEDULED"],
].map(([examinationId, examCode, examName, groupId, programId, programName, examPattern, examType, scheduleMode, totalMarks, passPercentage, subjectIds, status]) => ({ examinationId, examCode, examName, boardId: 1, academicYearId: 1, academicLevelId: 1, groupId, programId, programName, examPattern, examType, scheduleMode, totalMarks, passPercentage, subjectIds, status }));
const FACULTY = [{ facultyId: 1, facultyCode: "FAC001", facultyName: "Deepa" }, { facultyId: 2, facultyCode: "FAC004", facultyName: "Priya" }, { facultyId: 3, facultyCode: "FAC009", facultyName: "Anil" }, { facultyId: 4, facultyCode: "FAC011", facultyName: "Kiran" }];
const STUDENTS = [[1, "101", "Aarav"], [2, "102", "Bhavya"], [3, "103", "Charan"], [4, "104", "Divya"], [5, "105", "Eshan"], [6, "106", "Farah"]].map(([studentId, rollNo, studentName]) => ({ studentId, rollNo, studentName }));
const subjectOf = (id) => SUBJECTS.find((item) => String(item.subjectId) === String(id));
const facultyOf = (id) => FACULTY.find((item) => String(item.facultyId) === String(id));
const examOf = (id) => EXAMS.find((item) => String(item.examinationId) === String(id));
const objectiveExam = (exam) => exam?.scheduleMode === "COMBINED" || String(exam?.examType).toLowerCase() === "objective";
const expectedSubjects = (exam) => (exam?.subjectIds || []).map(subjectOf).filter(Boolean).filter((subject) => !objectiveExam(exam) || subject.category === "CORE");
const passingScore = (exam) => Math.ceil((exam.totalMarks * exam.passPercentage) / 100);
const gradeFor = (value) => value >= 90 ? "A+" : value >= 80 ? "A" : value >= 70 ? "B+" : value >= 60 ? "B" : value >= 50 ? "C" : value >= 40 ? "D" : "F";
const regularMarks = (subjectId, practical, offset) => STUDENTS.map((student, index) => {
  const internal = 16 + ((index + offset) % 5), practicalMark = practical ? 17 + ((index + offset) % 4) : null;
  const theory = practical ? 50 + ((index + offset) % 10) : 62 + ((index + offset) % 15);
  return { ...student, subjectId, internal, practical: practicalMark, theory, total: internal + (practicalMark || 0) + theory, remarks: "Reviewed", absent: false };
});
const objectiveMarks = (subjectId, offset) => STUDENTS.map((student, index) => ({ ...student, subjectId, obtainedMarks: 48 + ((index * 4 + offset) % 25), maxMarks: 75, remarks: "Reviewed", absent: false }));
const makeEvaluation = (evaluationId, examinationId, sectionId, subjectId, facultyId, status, rows, extra = {}) => ({
  evaluationId, examinationId, sectionId, subjectId, facultyId, status, rows,
  programId: examOf(examinationId).programId, groupId: examOf(examinationId).groupId,
  subjectMaxMarks: objectiveExam(examOf(examinationId)) ? 75 : 100,
  adminReviewMessage: "", rejectionReason: "", lastReviewedAt: "", resubmissionCount: 0, reviewHistory: [], ...extra,
});
const INITIAL_EVALUATIONS = [
  makeEvaluation(1, 1, 1, 101, 1, "SUBMITTED", regularMarks(101, false, 0)),
  makeEvaluation(2, 1, 1, 102, 4, "SUBMITTED", regularMarks(102, false, 1), { resubmissionCount: 1, rejectionReason: "Correct totals and resubmit.", reviewHistory: [{ action: "REJECTED", message: "Correct totals and resubmit.", actor: "Admin" }, { action: "RESUBMITTED", message: "Faculty corrected marks.", actor: "Faculty" }] }),
  makeEvaluation(3, 1, 1, 103, 3, "VERIFIED", regularMarks(103, false, 2), { adminReviewMessage: "Marks cross-checked with the submitted sheet." }),
  makeEvaluation(4, 1, 1, 104, 3, "APPROVED", regularMarks(104, false, 3)),
  makeEvaluation(5, 1, 1, 105, 2, "SUBMITTED", regularMarks(105, true, 4)), makeEvaluation(6, 1, 1, 106, 3, "SUBMITTED", regularMarks(106, true, 5)),
  makeEvaluation(7, 2, 2, 103, 3, "SUBMITTED", objectiveMarks(103, 0)), makeEvaluation(8, 2, 2, 104, 3, "VERIFIED", objectiveMarks(104, 2)),
  makeEvaluation(9, 2, 2, 105, 2, "SUBMITTED", objectiveMarks(105, 4)), makeEvaluation(10, 2, 2, 106, 3, "APPROVED", objectiveMarks(106, 6)),
  makeEvaluation(11, 3, 3, 201, 2, "SUBMITTED", objectiveMarks(201, 1)), makeEvaluation(12, 3, 3, 202, 2, "SUBMITTED", objectiveMarks(202, 3)),
  makeEvaluation(13, 3, 3, 203, 3, "VERIFIED", objectiveMarks(203, 5)), makeEvaluation(14, 3, 3, 204, 3, "APPROVED", objectiveMarks(204, 7)),
];
const obtained = (row, objective) => objective ? Number(row.obtainedMarks) : Number(row.total);
const validEvaluation = (record, exam) => record.rows.length > 0 && record.rows.every((row) => {
  if (objectiveExam(exam)) return row.absent ? row.obtainedMarks == null : Number.isFinite(Number(row.obtainedMarks)) && Number(row.maxMarks) > 0 && Number(row.obtainedMarks) >= 0 && Number(row.obtainedMarks) <= Number(row.maxMarks);
  if (row.absent) return row.internal == null && row.practical == null && row.theory == null && row.total == null;
  const practical = subjectOf(record.subjectId).practical, internal = Number(row.internal), practicalMark = practical ? Number(row.practical) : 0, theory = Number(row.theory), total = Number(row.total);
  return [internal, practicalMark, theory, total].every(Number.isFinite) && internal >= 0 && internal <= 20 && practicalMark >= 0 && practicalMark <= (practical ? 20 : 0) && theory >= 0 && theory <= (practical ? 60 : 80) && total === internal + practicalMark + theory && total <= record.subjectMaxMarks;
});

export default function MarksEntryPage() {
  const emptyFilters = { board: "", academicYear: "", academicLevel: "", group: "", program: "", section: "", examination: "" };
  const [filters, setFilters] = useState(emptyFilters), [applied, setApplied] = useState(null), [evaluations, setEvaluations] = useState(INITIAL_EVALUATIONS);
  const [tab, setTab] = useState("evaluations"), [search, setSearch] = useState(""), [studentSearch, setStudentSearch] = useState("");
  const [evaluationId, setEvaluationId] = useState(null), [studentId, setStudentId] = useState(null), [page, setPage] = useState(1), [studentPage, setStudentPage] = useState(1);
  const [toast, setToast] = useState(null), [decision, setDecision] = useState(null), [message, setMessage] = useState(""), [globalStage, setGlobalStage] = useState(null);
  const toastRef = useRef(null);
  const showToast = useCallback((msg, type = "success") => { if (toastRef.current) clearTimeout(toastRef.current); setToast({ msg, type }); toastRef.current = setTimeout(() => setToast(null), 3500); }, []);
  useEffect(() => () => toastRef.current && clearTimeout(toastRef.current), []);
  const exam = useMemo(() => examOf(applied?.examination), [applied]), section = useMemo(() => SECTIONS.find((item) => String(item.sectionId) === String(applied?.section)), [applied]);
  const subjects = useMemo(() => expectedSubjects(exam), [exam]);
  const contextEvaluations = useMemo(() => {
    if (!exam || !section) return [];
    const allowed = new Set(subjects.map((item) => String(item.subjectId)));
    const matches = evaluations.filter((item) => String(item.examinationId) === String(exam.examinationId) && String(item.sectionId) === String(section.sectionId) && item.programId === exam.programId && item.groupId === exam.groupId && allowed.has(String(item.subjectId)) && item.status !== "DRAFT");
    const counts = matches.reduce((map, item) => map.set(String(item.subjectId), (map.get(String(item.subjectId)) || 0) + 1), new Map());
    return matches.filter((item) => counts.get(String(item.subjectId)) === 1);
  }, [evaluations, exam, section, subjects]);
  const selectedEvaluation = contextEvaluations.find((item) => String(item.evaluationId) === String(evaluationId));
  const options = {
    boards: BOARDS.map((item) => [item.boardId, item.boardName]),
    years: YEARS.filter((item) => String(item.boardId) === filters.board).map((item) => [item.academicYearId, item.academicYearName]),
    levels: LEVELS.filter((item) => String(item.boardId) === filters.board && String(item.academicYearId) === filters.academicYear).map((item) => [item.academicLevelId, item.levelName]),
    groups: GROUPS.filter((item) => String(item.academicLevelId) === filters.academicLevel).map((item) => [item.groupId, item.groupName]),
    programs: PROGRAMS.filter((item) => item.groupIds.some((id) => String(id) === filters.group)).map((item) => [item.programId, item.programName]),
    sections: SECTIONS.filter((item) => String(item.boardId) === filters.board && String(item.academicYearId) === filters.academicYear && String(item.academicLevelId) === filters.academicLevel && String(item.groupId) === filters.group && String(item.programId) === filters.program).map((item) => [item.sectionId, item.sectionName]),
    exams: EXAMS.filter((item) => item.status === "COMPLETED" && String(item.boardId) === filters.board && String(item.academicYearId) === filters.academicYear && String(item.academicLevelId) === filters.academicLevel && String(item.groupId) === filters.group && String(item.programId) === filters.program).map((item) => [item.examinationId, item.examName]),
  };
  const changeFilter = (key, value) => { const order = ["board", "academicYear", "academicLevel", "group", "program", "section", "examination"]; setFilters((current) => ({ ...current, ...Object.fromEntries(order.slice(order.indexOf(key) + 1).map((item) => [item, ""])), [key]: value })); setApplied(null); setEvaluationId(null); setStudentId(null); };
  const allSelected = Object.values(filters).every(Boolean);
  const checkData = () => { if (!allSelected) return showToast("Select all 7 evaluation filters.", "error"); setApplied({ ...filters }); setEvaluationId(null); setStudentId(null); setTab("evaluations"); setPage(1); setStudentPage(1); };
  const evaluationRows = contextEvaluations.map((item) => { const subject = subjectOf(item.subjectId), faculty = facultyOf(item.facultyId), marks = item.rows.filter((row) => !row.absent).map((row) => obtained(row, objectiveExam(exam))); return { ...item, subject, faculty, average: marks.length ? (marks.reduce((sum, mark) => sum + mark, 0) / marks.length).toFixed(2) : "—", highest: marks.length ? Math.max(...marks) : "—", lowest: marks.length ? Math.min(...marks) : "—" }; });
  const filteredEvaluations = evaluationRows.filter((item) => `${item.subject.subjectName} ${item.faculty.facultyName} ${item.status}`.toLowerCase().includes(search.toLowerCase()));
  const analysis = useMemo(() => STUDENTS.map((student) => { const marks = {}; subjects.forEach((subject) => { const record = contextEvaluations.find((item) => String(item.subjectId) === String(subject.subjectId)), row = record?.rows.find((item) => item.studentId === student.studentId); marks[String(subject.subjectId)] = row ? row.absent ? "A" : obtained(row, objectiveExam(exam)) : "—"; }); const total = Object.values(marks).filter((value) => Number.isFinite(Number(value))).map(Number).reduce((sum, value) => sum + value, 0), maximum = Number(exam?.totalMarks || 0), percentage = total >= 0 && total <= maximum && maximum > 0 ? total / maximum * 100 : null; return { ...student, marks, total, maximum, percentage, grade: percentage == null ? "—" : gradeFor(percentage), result: percentage == null ? "—" : percentage >= exam.passPercentage ? "PASS" : "FAIL" }; }), [contextEvaluations, exam, subjects]);
  const filteredStudents = analysis.filter((item) => `${item.rollNo} ${item.studentName}`.toLowerCase().includes(studentSearch.toLowerCase())), studentPages = Math.max(1, Math.ceil(filteredStudents.length / PAGE_SIZE)), pagedStudents = filteredStudents.slice((studentPage - 1) * PAGE_SIZE, studentPage * PAGE_SIZE), selectedStudent = analysis.find((item) => String(item.studentId) === String(studentId));
  const submitted = contextEvaluations.filter((item) => item.status === "SUBMITTED"), verified = contextEvaluations.filter((item) => item.status === "VERIFIED"), globalAction = submitted.length ? "VERIFY_ALL" : verified.length ? "APPROVE_ALL" : null;
  const readyForResults = subjects.length > 0 && subjects.every((subject) => { const matches = contextEvaluations.filter((item) => String(item.subjectId) === String(subject.subjectId)); return matches.length === 1 && matches[0].status === "APPROVED"; });
  const update = (id, values) => setEvaluations((current) => current.map((item) => item.evaluationId === id ? { ...item, ...values } : item));
  const confirmDecision = () => { if (!selectedEvaluation || message.trim().length < 5) return; if (decision === "VERIFY" && !validEvaluation(selectedEvaluation, exam)) return showToast(`Cannot verify ${subjectOf(selectedEvaluation.subjectId).subjectName}. One or more student mark records are invalid.`, "error"); const status = decision === "VERIFY" ? "VERIFIED" : "REJECTED", text = message.trim(); update(selectedEvaluation.evaluationId, { status, adminReviewMessage: decision === "VERIFY" ? text : selectedEvaluation.adminReviewMessage, rejectionReason: decision === "REJECT" ? text : selectedEvaluation.rejectionReason, lastReviewedAt: new Date().toISOString(), reviewHistory: [...selectedEvaluation.reviewHistory, { action: status, message: text, actor: "Admin" }] }); setDecision(null); setMessage(""); showToast(`Evaluation ${status.toLowerCase()} successfully.`); };
  const approve = () => { if (selectedEvaluation?.status !== "VERIFIED") return showToast("Only VERIFIED evaluations can be approved.", "error"); update(selectedEvaluation.evaluationId, { status: "APPROVED", lastReviewedAt: new Date().toISOString() }); showToast("Evaluation approved successfully."); };
  const confirmGlobal = () => { if (globalStage === "VERIFY_ALL") { const invalid = submitted.find((item) => !validEvaluation(item, exam)); if (invalid) { setGlobalStage(null); return showToast(`Verify All cannot continue. ${subjectOf(invalid.subjectId).subjectName} contains invalid marks.`, "error"); } const ids = new Set(submitted.map((item) => item.evaluationId)); setEvaluations((current) => current.map((item) => ids.has(item.evaluationId) ? { ...item, status: "VERIFIED", adminReviewMessage: "Verified through global review.", lastReviewedAt: new Date().toISOString(), reviewHistory: [...item.reviewHistory, { action: "VERIFIED", message: "Verified through global review.", actor: "Admin" }] } : item)); showToast("All eligible submitted evaluations verified."); } else { const ids = new Set(verified.map((item) => item.evaluationId)); setEvaluations((current) => current.map((item) => ids.has(item.evaluationId) ? { ...item, status: "APPROVED", lastReviewedAt: new Date().toISOString() } : item)); showToast("All VERIFIED evaluations approved."); } setGlobalStage(null); };
  const display = { group: GROUPS.find((item) => String(item.groupId) === String(applied?.group))?.groupName || "—", program: PROGRAMS.find((item) => String(item.programId) === String(applied?.program))?.programName || "—", section: section?.sectionName || "—", examination: exam?.examName || "—" };

  return <DashboardLayout title="Marks Evaluation" subtitle="Review and approve faculty-submitted examination marks" breadcrumb={["Marks Evaluation"]}><div className="cms-marks-entry">
    {toast && <div className={`cms-toast-banner cms-toast-${toast.type}`}>{toast.msg}</div>}
    <section className="cms-card cms-card-filter"><div className="cms-section-heading"><div><h2>Evaluation Filters</h2><p>Select the completed examination context to review faculty submissions.</p></div><button className="cms-btn cms-btn-primary" disabled={!allSelected} onClick={checkData}>Check Evaluation Data</button></div><div className="cms-filter-grid">
      <Filter label="Board" value={filters.board} options={options.boards} onChange={(v) => changeFilter("board", v)} /><Filter label="Academic Year" value={filters.academicYear} options={options.years} disabled={!filters.board} onChange={(v) => changeFilter("academicYear", v)} /><Filter label="Academic Level" value={filters.academicLevel} options={options.levels} disabled={!filters.academicYear} onChange={(v) => changeFilter("academicLevel", v)} /><Filter label="Group" value={filters.group} options={options.groups} disabled={!filters.academicLevel} onChange={(v) => changeFilter("group", v)} /><Filter label="Program" value={filters.program} options={options.programs} disabled={!filters.group} onChange={(v) => changeFilter("program", v)} /><Filter label="Section" value={filters.section} options={options.sections} disabled={!filters.program} onChange={(v) => changeFilter("section", v)} /><Filter label="Examination" value={filters.examination} options={options.exams} disabled={!filters.section} onChange={(v) => changeFilter("examination", v)} />
    </div></section>
    {applied ? selectedEvaluation ? <EvaluationDetails evaluation={selectedEvaluation} exam={exam} display={display} page={page} setPage={setPage} onBack={() => setEvaluationId(null)} onVerify={() => { setDecision("VERIFY"); setMessage(""); }} onReject={() => { setDecision("REJECT"); setMessage(""); }} onApprove={approve} /> : selectedStudent ? <StudentDetails student={selectedStudent} exam={exam} subjects={subjects} evaluations={contextEvaluations} display={display} onBack={() => setStudentId(null)} /> : <section className="cms-card cms-main-card">
      <div className="cms-detail-grid"><Card label="Exam Pattern" value={exam.examPattern} /><Card label="Exam Type" value={exam.examType} /><Card label="Total Marks" value={exam.totalMarks} /><Card label="Pass Percentage" value={`${exam.passPercentage}%`} /></div>
      <div className="cms-table-toolbar"><div className="cms-tab-bar"><button className={`cms-tab-btn ${tab === "evaluations" ? "cms-active" : ""}`} onClick={() => setTab("evaluations")}>Evaluation</button><button className={`cms-tab-btn ${tab === "students" ? "cms-active" : ""}`} onClick={() => setTab("students")}>Student Analysis</button></div><div className="cms-search-wrap"><span className="cms-search-icon">⌕</span><input className="cms-search-input" value={tab === "evaluations" ? search : studentSearch} onChange={(e) => { if (tab === "evaluations") setSearch(e.target.value); else { setStudentSearch(e.target.value); setStudentPage(1); } }} placeholder={tab === "evaluations" ? "Search subject, faculty, status..." : "Search roll number or student..."} /></div>{tab === "evaluations" && globalAction && <button className={`cms-btn ${globalAction === "VERIFY_ALL" ? "cms-btn-info" : "cms-btn-success"}`} onClick={() => setGlobalStage(globalAction)}>{globalAction === "VERIFY_ALL" ? "Verify All" : "Approve All"}</button>}</div>
      {tab === "evaluations" ? <EvaluationTable rows={filteredEvaluations} onClick={(item) => { setEvaluationId(item.evaluationId); setPage(1); }} /> : <StudentTable rows={pagedStudents} subjects={subjects} exam={exam} onClick={(item) => setStudentId(item.studentId)} />}{tab === "students" && <><p className="cms-analysis-status">{readyForResults ? "All subject evaluations approved. Ready for Results." : "Evaluation in progress"}</p><Pagination page={studentPage} total={studentPages} setPage={setStudentPage} /></>}
    </section> : <div className="cms-card cms-empty-table"><p>Select all 7 evaluation filters and click <strong>Check Evaluation Data</strong> to view evaluation status &amp; student marks.</p></div>}
    {decision && <MessageModal title={decision === "VERIFY" ? "Verify Evaluation" : "Reject Evaluation"} label={decision === "VERIFY" ? "Admin Review Message" : "Correction Message"} value={message} setValue={setMessage} danger={decision === "REJECT"} onCancel={() => setDecision(null)} onConfirm={confirmDecision} />}
    {globalStage && <ConfirmModal title={globalStage === "VERIFY_ALL" ? "Verify All Evaluations" : "Approve All Evaluations"} message={globalStage === "VERIFY_ALL" ? `Verify All will apply to ${submitted.length} SUBMITTED evaluations in this selection context.` : `Approve All will apply to ${verified.length} VERIFIED evaluations in this selection context.`} onCancel={() => setGlobalStage(null)} onConfirm={confirmGlobal} />}
  </div></DashboardLayout>;
}

function Filter({ label, value, options, disabled, onChange }) { return <div className="cms-field-group"><label className="cms-field-label">{label}</label><select className="cms-select-input" value={value} disabled={disabled} onChange={(e) => onChange(e.target.value)}><option value="">Select {label}</option>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div>; }
function EvaluationTable({ rows, onClick }) { return <div className="cms-table-container"><table className="cms-table"><thead><tr><th>SUBJECT</th><th>FACULTY</th><th>STUDENTS</th><th>AVERAGE / MAX</th><th>HIGHEST</th><th>LOWEST</th><th>STATUS</th></tr></thead><tbody>{rows.length ? rows.map((item) => <tr className="cms-clickable-row" key={item.evaluationId} onClick={() => onClick(item)}><td className="cms-font-semibold">{item.subject.subjectName}<small className="cms-row-subtitle">{item.subject.subjectCode}</small></td><td>{item.faculty.facultyName} - {item.faculty.facultyCode}</td><td className="cms-text-center">{item.rows.length}</td><td className="cms-text-center">{item.average} / {item.subjectMaxMarks}</td><td className="cms-text-center">{item.highest}</td><td className="cms-text-center">{item.lowest}</td><td className="cms-text-center"><Badge status={item.status} /></td></tr>) : <tr><td colSpan={7} className="cms-empty-td">No submitted evaluation records are available.</td></tr>}</tbody></table></div>; }
function StudentTable({ rows, subjects, exam, onClick }) { return <div className="cms-table-container"><table className="cms-table"><thead><tr><th>ROLL NO</th><th>STUDENT</th>{subjects.map((s) => <th key={s.subjectId}>{s.subjectName}</th>)}<th>TOTAL / EXAM TOTAL</th><th>PERCENTAGE</th><th>GRADE</th><th>RESULT</th></tr></thead><tbody>{rows.map((student) => <tr className="cms-clickable-row" key={student.studentId} onClick={() => onClick(student)}><td className="cms-font-semibold">{student.rollNo}</td><td>{student.studentName}</td>{subjects.map((s) => <td className="cms-text-center" key={s.subjectId}>{student.marks[String(s.subjectId)]}</td>)}<td className="cms-text-center">{student.total} / {exam.totalMarks}</td><td className="cms-text-center">{student.percentage == null ? "—" : `${student.percentage.toFixed(2)}%`}</td><td className="cms-text-center">{student.grade}</td><td className="cms-text-center">{student.result}</td></tr>)}</tbody></table></div>; }
function EvaluationDetails({ evaluation, exam, display, page, setPage, onBack, onVerify, onReject, onApprove }) { const subject = subjectOf(evaluation.subjectId), faculty = facultyOf(evaluation.facultyId), total = Math.max(1, Math.ceil(evaluation.rows.length / PAGE_SIZE)), rows = evaluation.rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); return <div className="cms-card cms-main-card cms-evaluation-details"><div className="cms-details-header"><div><button className="cms-back-btn" onClick={onBack}>← Back to Evaluations</button><h2 className="cms-details-title">{subject.subjectName} ({subject.subjectCode}) Evaluation Marks Breakdown</h2><span className="cms-details-subtitle">Review faculty-submitted student marks for this subject</span></div></div><div className="cms-detail-grid"><Card label="Faculty" value={`${faculty.facultyName} - ${faculty.facultyCode}`} /><Card label="Group" value={display.group} /><Card label="Program" value={display.program} /><Card label="Section" value={display.section} /><Card label="Examination" value={display.examination} /><Card label="Exam Type" value={exam.examType} /><Card label="Subject Max Marks" value={evaluation.subjectMaxMarks} /><Card label="Exam Pattern" value={exam.examPattern} /></div><MarksTable rows={rows} objective={objectiveExam(exam)} practical={subject.practical} /><Pagination page={page} total={total} setPage={setPage} /><div className="cms-modal-actions">{evaluation.status === "SUBMITTED" && <><button className="cms-btn cms-btn-info" onClick={onVerify}><Check /> Verify</button><button className="cms-btn cms-btn-danger" onClick={onReject}><Cross /> Reject</button></>}{evaluation.status === "VERIFIED" && <><button className="cms-btn cms-btn-success" onClick={onApprove}><Check /> Approve</button><button className="cms-btn cms-btn-danger" onClick={onReject}><Cross /> Reject</button></>}{evaluation.status === "APPROVED" && <span className="cms-status-pill cms-status-approved"><Check /> Approved</span>}{evaluation.status === "REJECTED" && <span className="cms-status-pill cms-status-rejected"><Cross /> Returned to Faculty for correction</span>}</div></div>; }
function MarksTable({ rows, objective, practical }) { return <div className="cms-table-container cms-details-table-wrap"><table className="cms-table cms-details-table"><thead><tr><th>ROLL NO</th><th>STUDENT NAME</th>{objective ? <><th>OBTAINED MARKS</th><th>MAX MARKS</th><th>PERCENTAGE</th></> : <><th>INTERNAL</th>{practical && <th>PRACTICAL</th>}<th>THEORY</th><th>TOTAL</th></>}<th>REMARKS</th><th>ABSENT</th></tr></thead><tbody>{rows.map((row) => <tr key={row.studentId}><td>{row.rollNo}</td><td>{row.studentName}</td>{objective ? <><td>{row.absent ? "—" : row.obtainedMarks}</td><td>{row.maxMarks}</td><td>{row.absent ? "—" : `${(row.obtainedMarks / row.maxMarks * 100).toFixed(2)}%`}</td></> : <><td>{row.absent ? "—" : row.internal}</td>{practical && <td>{row.absent ? "—" : row.practical}</td>}<td>{row.absent ? "—" : row.theory}</td><td>{row.absent ? "—" : row.total}</td></>}<td>{row.remarks}</td><td>{row.absent ? "Yes" : "No"}</td></tr>)}</tbody></table></div>; }
function StudentDetails({ student, exam, subjects, evaluations, display, onBack }) { const objective = objectiveExam(exam), details = subjects.map((subject) => { const record = evaluations.find((item) => String(item.subjectId) === String(subject.subjectId)), row = record?.rows.find((item) => item.studentId === student.studentId); return { subject, row, max: record?.subjectMaxMarks || "—" }; }); return <div className="cms-card cms-main-card cms-student-details"><div className="cms-details-header"><div><button className="cms-back-btn" onClick={onBack}>← Back To Student Analysis</button><h2 className="cms-details-title">Student Detailed Report</h2></div></div><div className="cms-detail-grid"><Card label="Roll Number" value={student.rollNo} /><Card label="Student Name" value={student.studentName} /><Card label="Group" value={display.group} /><Card label="Program" value={display.program} /><Card label="Section" value={display.section} /><Card label="Examination" value={display.examination} /><Card label="Exam Type" value={exam.examType} /><Card label="Percentage" value={`${student.percentage.toFixed(2)}%`} /><Card label="Grade" value={student.grade} /><Card label="Result" value={student.result} /></div><div className="cms-table-container cms-details-table-wrap"><table className="cms-table"><thead><tr><th>SUBJECT</th>{objective ? <><th>OBTAINED</th><th>MAX</th><th>PERCENTAGE</th></> : <><th>INTERNAL</th><th>PRACTICAL</th><th>THEORY</th><th>TOTAL</th></>}</tr></thead><tbody>{details.map(({ subject, row, max }) => <tr key={subject.subjectId}><td>{subject.subjectName}</td>{objective ? <><td>{row?.obtainedMarks ?? "—"}</td><td>{max}</td><td>{row ? `${(row.obtainedMarks / row.maxMarks * 100).toFixed(2)}%` : "—"}</td></> : <><td>{row?.internal ?? "—"}</td><td>{subject.practical ? row?.practical ?? "—" : "—"}</td><td>{row?.theory ?? "—"}</td><td>{row?.total ?? "—"}</td></>}</tr>)}</tbody></table></div><div className="cms-details-section"><h3 className="cms-details-section-title">Performance Summary</h3><div className="cms-detail-grid"><Card label="Overall Total" value={student.total} /><Card label="Maximum" value={exam.totalMarks} /><Card label="Percentage" value={`${student.percentage.toFixed(2)}%`} /><Card label="Pass Percentage" value={`${exam.passPercentage}%`} /><Card label="Passing Score" value={passingScore(exam)} /><Card label="Grade" value={student.grade} /><Card label="Result" value={student.result} /></div></div></div>; }
function MessageModal({ title, label, value, setValue, danger, onCancel, onConfirm }) { return <div className="cms-overlay"><div className="cms-modal sm"><div className="cms-modal-head"><h3>{title}</h3></div><div className="cms-modal-body"><div className="cms-field-group"><label className="cms-field-label">{label}</label><textarea className="cms-marks-textarea" rows={4} value={value} onChange={(e) => setValue(e.target.value)} placeholder="Enter at least 5 characters" /></div></div><div className="cms-modal-foot"><button className="cms-btn" onClick={onCancel}>Cancel</button><button className={`cms-btn ${danger ? "cms-btn-danger" : "cms-btn-info"}`} disabled={value.trim().length < 5} onClick={onConfirm}>{danger ? "Confirm Reject" : "Confirm Verify"}</button></div></div></div>; }
function ConfirmModal({ title, message, onCancel, onConfirm }) { return <div className="cms-overlay"><div className="cms-modal sm"><div className="cms-modal-head"><h3>{title}</h3></div><div className="cms-modal-body">{message}</div><div className="cms-modal-foot"><button className="cms-btn" onClick={onCancel}>Cancel</button><button className="cms-btn cms-btn-primary" onClick={onConfirm}>Confirm</button></div></div></div>; }
function Pagination({ page, total, setPage }) { return <div className="cms-pagination"><button className="cms-page-btn" disabled={page === 1} onClick={() => setPage((v) => Math.max(1, v - 1))}>Previous</button><span>Page {page} of {total}</span><button className="cms-page-btn" disabled={page === total} onClick={() => setPage((v) => Math.min(total, v + 1))}>Next</button></div>; }
function Card({ label, value }) { return <div className="cms-detail-card"><span className="cms-detail-label">{label}</span><span className="cms-detail-value">{value}</span></div>; }
function Badge({ status }) { const meta = STATUS_META[status] || STATUS_META.SUBMITTED; return <span className={`cms-badge-status ${meta[1]}`}><span className="cms-badge-dot" />{meta[0]}</span>; }
