import React, { useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { FiCheckCircle, FiEdit2, FiSave, FiShield, FiX, FiXCircle } from "react-icons/fi";
import DashboardLayout from "../layout/DashboardLayout";
import "./MarksEntryPage.css";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "https://sterile-retorted-tightness.ngrok-free.dev";
// TODO: Replace TEMP data with API response when the evaluation backend is ready.
const TEMP_EVALUATIONS = [{ evaluationId: 1, subjectName: "English", facultyName: "Lakshmi", studentsCount: 60, status: "SUBMITTED" }, { evaluationId: 2, subjectName: "Sanskrit", facultyName: "Suresh", studentsCount: 60, status: "SUBMITTED" }, { evaluationId: 3, subjectName: "Mathematics", facultyName: "Ravi Kumar", studentsCount: 60, status: "VERIFIED" }, { evaluationId: 4, subjectName: "Physics", facultyName: "Naresh", studentsCount: 60, status: "APPROVED" }, { evaluationId: 5, subjectName: "Chemistry", facultyName: "Kiran", studentsCount: 60, status: "SUBMITTED" }];
const TEMP_RESULTS = [{ studentId: 1, rollNo: "MPC001", studentName: "Rahul", group: "MPC", totalMarks: 438, percentage: 87.6, grade: "A", result: "PASS" }, { studentId: 2, rollNo: "MPC002", studentName: "Ramesh", group: "MPC", totalMarks: 418, percentage: 83.6, grade: "A", result: "PASS" }];
const TEMP_STUDENT_MARKS = [{ studentId: 1, rollNo: "MPC001", studentName: "Rahul", subjects: { English: 85, Sanskrit: 78, Mathematics: 92, Physics: 88, Chemistry: 95 }, total: 438, grade: "A" }, { studentId: 2, rollNo: "MPC002", studentName: "Ramesh", subjects: { English: 80, Sanskrit: 76, Mathematics: 88, Physics: 84, Chemistry: 90 }, total: 418, grade: "A" }];
const GROUP_SUBJECTS = { MPC: ["English", "Sanskrit", "Mathematics", "Physics", "Chemistry"], BIPC: ["English", "Sanskrit", "Biology", "Physics", "Chemistry"], CEC: ["English", "Sanskrit", "Civics", "Economics", "Commerce"], HEC: ["English", "Sanskrit", "History", "Economics", "Civics"] };
const flow = { board: ["BIE Telangana", "BIE Andhra Pradesh", "CBSE"], academicYear: ["2025-2026", "2026-2027"], academicLevel: ["Intermediate 1st Year", "Intermediate 2nd Year"], group: Object.keys(GROUP_SUBJECTS), section: ["A", "B"], examination: ["Semester I", "Semester II"] };
const blank = { board: "", academicYear: "", academicLevel: "", group: "", section: "", examination: "" };
const PRACTICAL_SUBJECTS = ["Physics", "Chemistry", "Botany", "Zoology"];
const MAX_MARKS_PER_SUBJECT = 100;
const totalOf = (m) => Number(m.internal || 0) + Number(m.theory || 0) + Number(m.practical || 0);
const gradeOf = (n) => n >= 90 ? "A+" : n >= 80 ? "A" : n >= 70 ? "B+" : n >= 60 ? "B" : n >= 50 ? "C" : n >= 40 ? "D" : "F";
const normalizedStatus = (status) => String(status || "SUBMITTED").toUpperCase();
async function request(path, options = {}) { const response = await fetch(`${API_BASE_URL}${path}`, options); if (!response.ok) throw new Error("Request failed"); return response.json(); }
function Badge({ status }) { const x = normalizedStatus(status); return <span className={`cms-badge-status cms-status-${x.toLowerCase()}`}><span className="cms-badge-dot" />{x}</span>; }
function Select({ label, value, disabled, onChange }) { return <div className="cms-field-group"><label className="cms-field-label">{label}</label><select className="cms-select-input" value={value} disabled={disabled} onChange={(e) => onChange(e.target.value)}><option value="">Select {label}</option>{flow[label === "Academic Year" ? "academicYear" : label === "Academic Level" ? "academicLevel" : label.toLowerCase()].map((x) => <option key={x}>{x}</option>)}</select></div>; }
function Summary({ evaluations }) { const c = (x) => evaluations.filter((e) => e.status === x).length; return <div className="cms-summary-grid">{[["Total Subjects", evaluations.length], ["Submitted", c("SUBMITTED")], ["Verified", c("VERIFIED")], ["Approved", c("APPROVED")], ["Rejected", c("REJECTED")]].map(([a, b]) => <div className="cms-stat-card" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>; }
function Modal({ title, close, children, className = "cms-evaluation-modal" }) { return createPortal(<div className="cms-modal-overlay"><div className={`cms-modal-content ${className}`} role="dialog" aria-modal="true"><div className="cms-section-heading"><h2>{title}</h2><button className="cms-btn-icon" title="Close" aria-label="Close" onClick={close}><FiX /></button></div>{children}</div></div>, document.body); }

export default function MarksEntry() {
  const [filters, setFilters] = useState(blank), [ready, setReady] = useState(false), [tab, setTab] = useState("evaluations"), [evaluations, setEvaluations] = useState(TEMP_EVALUATIONS), [evaluation, setEvaluation] = useState(null), [editing, setEditing] = useState(false), [rows, setRows] = useState([]);
  const subjects = GROUP_SUBJECTS[filters.group || "MPC"];
  const change = (key, value) => setFilters((p) => ({ ...p, [key]: value, ...(key === "board" ? { academicYear: "", academicLevel: "", group: "", section: "", examination: "" } : {}), ...(key === "academicYear" ? { academicLevel: "", group: "", section: "", examination: "" } : {}), ...(key === "academicLevel" ? { group: "", section: "", examination: "" } : {}), ...(key === "group" ? { section: "", examination: "" } : {}), ...(key === "section" ? { examination: "" } : {}) }));
  const open = (item) => { const practical = PRACTICAL_SUBJECTS.includes(item.subjectName); setRows(TEMP_RESULTS.map((x, i) => ({ ...x, internal: 20 + i, theory: practical ? 60 + i * 3 : 65 + i * 3, practical: practical ? 18 + i : 0 }))); setEditing(false); setEvaluation(item); };
  const status = (id, s) => { setEvaluations((old) => old.map((x) => x.evaluationId === id ? { ...x, status: s } : x)); setEvaluation((current) => current?.evaluationId === id ? { ...current, status: s } : current); };
  const updateMark = (i, k, v) => /^\d*$/.test(v) && setRows((old) => old.map((x, j) => j === i ? { ...x, [k]: v } : x));
  return <DashboardLayout title="Academic Evaluation" subtitle="Review, verify and approve faculty submitted evaluations." breadcrumb={["Examinations"]}>
    <section className="cms-marks-entry cms-anim-up"><div className="cms-card cms-card-filter">
    <div className="cms-section-heading"><div><h2>Evaluation Filters</h2><p>Choose the academic context before reviewing faculty submissions.</p></div><button className="cms-btn cms-btn-primary" onClick={() => Object.values(filters).every(Boolean) && setReady(true)}>Fetch Evaluation Data</button></div><div className="cms-filter-grid"><Select label="Board" value={filters.board} onChange={(v) => change("board", v)}/><Select label="Academic Year" value={filters.academicYear} disabled={!filters.board} onChange={(v) => change("academicYear", v)}/><Select label="Academic Level" value={filters.academicLevel} disabled={!filters.academicYear} onChange={(v) => change("academicLevel", v)}/><Select label="Group" value={filters.group} disabled={!filters.academicLevel} onChange={(v) => change("group", v)}/><Select label="Section" value={filters.section} disabled={!filters.group} onChange={(v) => change("section", v)}/><Select label="Examination" value={filters.examination} disabled={!filters.section} onChange={(v) => change("examination", v)}/></div></div>{ready ? <><Summary evaluations={evaluations}/><div className="cms-card"><div className="cms-table-toolbar"><div className="cms-tab-bar">{[["evaluations", "Evaluations"], ["marks", "Student Subject Marks"]].map(([a, b]) => <button className={`cms-tab-btn ${tab === a ? "cms-active" : ""}`} key={a} onClick={() => setTab(a)}>{b}</button>)}</div></div>{tab === "evaluations" ? <EvaluationTable items={evaluations} open={open}/> : <MarksTable items={TEMP_STUDENT_MARKS} subjects={subjects}/>}</div></> : <div className="cms-card cms-empty-table">Select all filters and fetch evaluation data </div>}{evaluation && <EvaluationModal item={evaluation} filters={filters} rows={rows} editing={editing} setEditing={setEditing} updateMark={updateMark} updateStatus={status} close={() => setEvaluation(null)}/>}</section></DashboardLayout>;
}
function EvaluationTable({ items, open }) { return <Table headers={["Subject", "Faculty", "Students", "Status"]}>{items.map((x) => <tr className="cms-clickable-row" key={x.evaluationId} onClick={() => open(x)}><td>{x.subjectName}</td><td>{x.facultyName}</td><td>{x.studentsCount}</td><td><Badge status={x.status}/></td></tr>)}</Table> }
function MarksTable({ items, subjects }) { return <Table cards headers={["Roll No", "Student", ...subjects, "Total", "Grade"]}>{items.map((x) => <tr key={x.studentId}><td data-label="Roll No">{x.rollNo}</td><td data-label="Student">{x.studentName}</td>{subjects.map((s) => <td data-label={s} key={s}>{x.subjects[s] ?? "—"}</td>)}<td data-label="Total">{x.total} / {subjects.length * MAX_MARKS_PER_SUBJECT}</td><td data-label="Grade">{x.grade}</td></tr>)}</Table> }
function Table({ headers, children, cards }) { return <div className={`cms-table-container cms-table-wrap ${cards ? "cms-responsive-cards" : ""}`}><table className="cms-table"><thead><tr>{headers.map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
function EvaluationModal({ item, filters, rows, editing, setEditing, updateMark, updateStatus, close }) { const practical = PRACTICAL_SUBJECTS.includes(item.subjectName), editable = ["SUBMITTED", "VERIFIED"].includes(item.status); return <Modal title={`${item.subjectName} Evaluation`} close={close}><Details item={item} filters={filters}/><Table headers={["Roll No", "Student Name", "Internal", "Theory", ...(practical ? ["Practical"] : []), "Total", "Grade"]}>{rows.map((x,i) => { const cell=(k)=><td key={k}>{editing && editable ? <input className="cms-mark-input" value={x[k]} onChange={(e)=>updateMark(i,k,e.target.value)}/> : x[k]}</td>, t=totalOf(x); return <tr key={x.studentId}><td>{x.rollNo}</td><td>{x.studentName}</td>{cell("internal")}{cell("theory")}{practical&&cell("practical")}<td>{t} / {MAX_MARKS_PER_SUBJECT}</td><td>{gradeOf(t)}</td></tr>})}</Table><div className="cms-modal-actions cms-sticky-actions">{editable&&<button className="cms-btn cms-btn-secondary" title="Edit" onClick={()=>setEditing(!editing)}><FiEdit2/> Edit</button>}{editing&&editable&&<button className="cms-btn cms-btn-primary" title="Save Changes" onClick={()=>setEditing(false)}><FiSave/> Save Changes</button>}{item.status==="SUBMITTED"&&<><button className="cms-btn cms-btn-success" title="Verify" onClick={()=>updateStatus(item.evaluationId,"VERIFIED")}><FiShield/> Verify</button><button className="cms-btn cms-btn-danger" title="Reject" onClick={()=>updateStatus(item.evaluationId,"REJECTED")}><FiXCircle/> Reject</button></>}{item.status==="VERIFIED"&&<button className="cms-btn cms-btn-primary" title="Approve" onClick={()=>updateStatus(item.evaluationId,"APPROVED")}><FiCheckCircle/> Approve</button>}</div></Modal> }
function Details({ item, filters }) { return <div className="cms-detail-grid">{[["Student Name",item.studentName],["Faculty",item.facultyName],["Roll Number",item.rollNo],["Group",item.group||filters.group],["Section",filters.section],["Examination",filters.examination]].filter(([,v])=>v).map(([a,b])=><div key={a}><strong>{a}</strong><p>{b}</p></div>)}</div> }
function ResultModal({ item, filters, close }) { const marks=TEMP_STUDENT_MARKS.find(x=>x.studentId===item.studentId); return <Modal title="Student Result" close={close} className="cms-result-modal"><Details item={item} filters={filters}/><SubjectRows rows={Object.entries(marks.subjects)}/><ResultSummary item={item}/></Modal> }
function SheetModal({ item, filters, subjects, close }) { const r=TEMP_RESULTS.find(x=>x.studentId===item.studentId); return <Modal title="Full Marksheet" close={close} className="cms-marksheet-modal"><Details item={item} filters={filters}/><SubjectRows rows={subjects.map(s=>[s,item.subjects[s]??0])}/><ResultSummary item={{...r,totalMarks:item.total,grade:item.grade}}/></Modal> }
function SubjectRows({ rows }) { return <Table headers={["Subject","Marks","Grade"]}>{rows.map(([s,m])=><tr key={s}><td>{s}</td><td>{m}</td><td>{gradeOf(m)}</td></tr>)}</Table> }
function ResultSummary({ item }) { return <div className="cms-summary-grid">{[["Total Marks",item.totalMarks],["Percentage",`${item.percentage}%`],["Grade",item.grade],["Result",item.result]].map(([a,b])=><div className="cms-stat-card" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div> }
