import { Link } from "react-router-dom";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import { StatusBadge } from "@/components/common/Ui.jsx";
import { studentById } from "@/data/studentManagementData.js";
import "./StudentManagementPage.css";

const Card = ({ title, children }) => <section className="cms-card"><div className="cms-card-head"><h2>{title}</h2></div><div className="cms-card-body">{children}</div></section>;
const Details = ({ items }) => <div className="cms-kv">{items.map(([key, value]) => <div key={key}><span>{key}</span><strong>{value || "—"}</strong></div>)}</div>;
export default function StudentProfilePage({ id }) {
  const student = studentById(id);
  if (!student) return <DashboardLayout title="Student Profile" breadcrumb={["People", "Students"]}><div className="cms-card"><div className="cms-empty">Student admission record was not found.</div></div></DashboardLayout>;
  const initials = student.name.split(" ").map((x) => x[0]).join("").slice(0, 2), fee = student.fee || { total: 0, paid: 0 }, attendance = student.attendance || {}, performance = student.performance || {};
  return <DashboardLayout title={student.name} subtitle={`Admission No: ${student.admissionNo}`} breadcrumb={["People", "Students"]} actions={<><Link className="cms-btn cms-btn-ghost" to="/dashboard/students">Back to list</Link><Link className="cms-btn cms-btn-primary" to={`/dashboard/students/${id}/enroll`}>{student.roll ? "Edit Assignment" : "Assign Student"}</Link></>}>
    <Card title="Student Profile"><div className="cms-profile-hero"><div className="cms-photo">{initials}</div><div><h2>{student.name}</h2><p className="cms-muted">Student ID: {student.studentId} · Admission No: {student.admissionNo} · Roll No: {student.roll || "Not assigned"}</p><StatusBadge value={student.status || "Pending assignment"}/></div></div></Card>
    <div className="cms-grid-2"><Card title="Basic Student Information"><Details items={[["Date of Birth", student.dob], ["Gender", student.gender], ["Mobile Number", student.mobile], ["Email", student.email], ["Admission Date", student.admissionDate], ["Student Status", student.status]]}/></Card><Card title="Academic Assignment"><Details items={[["Board", student.board], ["Academic Year", student.academicYear], ["Academic Level", student.level], ["Group", student.group], ["Programme", student.programme], ["Section", student.section && `Section ${student.section}`], ["Roll Number", student.roll], ["Enrollment Status", student.status]]}/></Card><Card title="Parent / Guardian Details"><Details items={[["Father Name", student.father], ["Mother Name", student.mother], ["Guardian Name", student.guardian], ["Guardian Mobile", student.guardianMobile || student.mobile], ["Guardian Email", student.guardianEmail], ["Address", student.address]]}/></Card><Card title="Admission Details"><Details items={[["Admission No", student.admissionNo], ["Admission Date", student.admissionDate], ["Admission Type", student.admissionType], ["Admission Status", student.admissionStatus], ["Previous School/College", student.previousSchool], ["Previous Qualification", student.qualification]]}/></Card></div>
    <div className="cms-grid-3"><Card title="Fee Summary"><Details items={[["Total Fee", `₹${fee.total.toLocaleString("en-IN")}`], ["Paid Amount", `₹${fee.paid.toLocaleString("en-IN")}`], ["Pending Amount", `₹${(fee.total - fee.paid).toLocaleString("en-IN")}`], ["Fee Status", fee.paid >= fee.total ? "Paid" : "Partial"]]}/></Card><Card title="Attendance Summary"><Details items={[["Attendance", attendance.percentage && `${attendance.percentage}%`], ["Present", attendance.present], ["Absent", attendance.absent], ["Working Days", attendance.working]]}/></Card><Card title="Academic Performance"><Details items={[["Overall Percentage", performance.percentage && `${performance.percentage}%`], ["Grade", performance.grade], ["Subjects", performance.subjects], ["Recent Performance", performance.recent]]}/></Card></div>
  </DashboardLayout>;
}
