import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import { Toast } from "@/components/common/Ui.jsx";
import { allStudents, saveAssignment, studentById } from "@/data/studentManagementData.js";

const groups = { MPC: ["MPC", "MPC with Computer Science"], BiPC: ["BiPC", "BiPC with Biotechnology"], CEC: ["CEC"] };
export default function StudentEnrollmentPage({ id }) {
  const student = studentById(id), navigate = useNavigate();
  const [form, setForm] = useState({ academicYear: student?.academicYear || "2026-2027", board: student?.board || "Board of Intermediate Education", level: student?.level || "Intermediate 1st Year", group: student?.group || "MPC", programme: student?.programme || "MPC", section: student?.section || "A" });
  const [message, setMessage] = useState("");
  const roll = useMemo(() => { const scoped = allStudents().filter((s) => s.id !== id && ["academicYear", "level", "group", "programme", "section"].every((key) => s[key] === form[key])); return String(Math.max(0, ...scoped.map((s) => Number(s.roll) || 0)) + 1).padStart(3, "0"); }, [form, id]);
  if (!student) return <DashboardLayout title="Academic Assignment" breadcrumb={["People", "Students"]}><div className="cms-card"><div className="cms-empty">Student admission record was not found.</div></div></DashboardLayout>;
  const change = (key) => (event) => { const value = event.target.value; setForm((current) => key === "group" ? { ...current, group: value, programme: groups[value][0] } : { ...current, [key]: value }); };
  const submit = (event) => { event.preventDefault(); saveAssignment(id, { ...form, roll, status: "Active" }); setMessage(`Student successfully assigned to ${form.group} → ${form.programme} → Section ${form.section} with Roll No. ${roll}`); window.setTimeout(() => navigate(`/dashboard/students/${id}`), 900); };
  return <DashboardLayout title="Academic Assignment" subtitle="Assign the admitted student to an academic context." breadcrumb={["People", "Students"]} actions={<Link to={`/dashboard/students/${id}`} className="cms-btn cms-btn-ghost">Back to profile</Link>}><form onSubmit={submit} className="cms-card"><div className="cms-card-body"><div className="cms-profile-hero"><div className="cms-photo">{student.name.split(" ").map((x) => x[0]).join("").slice(0,2)}</div><div><h2>{student.name}</h2><p className="cms-muted">Student ID: {student.studentId} · Admission No: {student.admissionNo}</p></div></div></div><div className="cms-card-head"><h2>Academic Assignment</h2></div><div className="cms-card-body"><div className="cms-form-grid">{[["Academic Year", "academicYear", ["2026-2027", "2025-2026"]], ["Board", "board", ["Board of Intermediate Education"]], ["Academic Level", "level", ["Intermediate 1st Year", "Intermediate 2nd Year"]], ["Group", "group", Object.keys(groups)], ["Programme", "programme", groups[form.group]], ["Section", "section", ["A", "B", "C"]]].map(([label, key, values]) => <label className="cms-field" key={key}><span>{label}</span><select value={form[key]} onChange={change(key)}>{values.map((value) => <option key={value}>{value}</option>)}</select></label>)}</div><div className="student-roll-preview"><span>Generated Roll No</span><strong>{roll}</strong><small>Generated from this academic year, level, group, programme and section.</small></div><button className="cms-btn cms-btn-primary" type="submit">Assign Student</button></div></form><Toast message={message} onClose={() => setMessage("")}/></DashboardLayout>;
}
