import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, ClipboardCheck, Edit3, GraduationCap, Plus, Send, Settings2, Sparkles } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout.jsx";
import "./TimetablePage.css";

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const PERIODS = [
  { id: "P1", start: "09:00", end: "09:45", type: "Class" },
  { id: "P2", start: "09:45", end: "10:30", type: "Class" },
  { id: "P3", start: "10:30", end: "11:15", type: "Class" },
  { id: "B1", start: "11:15", end: "11:30", type: "Break" },
  { id: "P4", start: "11:30", end: "12:15", type: "Class" },
  { id: "P5", start: "12:15", end: "01:00", type: "Class" },
  { id: "P6", start: "01:30", end: "02:15", type: "Class" },
];
const SECTIONS = ["MPC-A", "MPC-B", "MPC-C", "MPC-D"];
const SUBJECTS = ["Mathematics", "Physics", "Chemistry", "English", "Physics Practical"];
const FACULTY = {
  Mathematics: ["Ravi Kumar"], Physics: ["Suresh Rao"], Chemistry: ["Kumar Das"], English: ["Priya Menon"], "Physics Practical": ["Suresh Rao"],
};
const ROOM = { "MPC-A": "Room 101", "MPC-B": "Room 102", "MPC-C": "Room 103", "MPC-D": "Room 104" };
const context = { academicYear: "2026-27", board: "BIEAP", level: "Intermediate", group: "MPC" };
const theory = ["Mathematics", "Physics", "English", "Chemistry", "Mathematics", "Physics"];

const initialSlots = () => SECTIONS.flatMap((section, sectionIndex) => DAYS.flatMap((day, dayIndex) => PERIODS.filter((period) => period.type === "Class").map((period, periodIndex) => {
  const subject = theory[(periodIndex + dayIndex + sectionIndex) % theory.length];
  return { id: `${section}-${day}-${period.id}`, section, day, period: period.id, subject, faculty: FACULTY[subject][0], room: ROOM[section], type: "Theory" };
})));

function Select({ value, onChange, options }) { return <select value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function Modal({ title, children, onClose }) { return <div className="ttm-overlay" onMouseDown={onClose}><section className="ttm-modal" onMouseDown={(e) => e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>; }
function Page({ title, subtitle, children, action }) { return <DashboardLayout title={title} subtitle={subtitle} breadcrumb={["Academics"]} actions={action}><main className="timetable-module">{children}</main></DashboardLayout>; }

function Setup() {
  const [days, setDays] = useState(DAYS);
  const [saved, setSaved] = useState(false);
  const toggleDay = (day) => setDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day]);
  return <Page title="Timetable Setup" subtitle="Configure the academic context, working days and period schedule." action={<Link className="ttm-secondary" to="/dashboard/timetable">Back</Link>}><section className="ttm-card ttm-setup"><div className="ttm-card-title"><Settings2/><div><h2>Academic configuration</h2><p>Period timing is defined here and is never changed by the generator.</p></div></div><div className="ttm-fields">{Object.entries(context).map(([key, value]) => <label key={key}>{key.replace(/([A-Z])/g, " $1")}<select defaultValue={value}><option>{value}</option></select></label>)}</div><h3>Working days</h3><div className="ttm-days">{[...DAYS, "Sunday"].map((day) => <label key={day}><input type="checkbox" checked={days.includes(day)} onChange={() => toggleDay(day)}/>{day.slice(0, 3)}</label>)}</div><h3>Period schedule</h3><div className="ttm-period-table"><div>Period</div><div>Start time</div><div>End time</div><div>Type</div>{PERIODS.map((period) => <><strong key={`${period.id}-id`}>{period.id}</strong><span key={`${period.id}-start`}>{period.start}</span><span key={`${period.id}-end`}>{period.end}</span><span key={`${period.id}-type`} className={period.type === "Break" ? "break" : ""}>{period.type}</span></>)}</div><div className="ttm-screen-nav"><button className="ttm-primary" onClick={() => setSaved(true)}><CheckCircle2/> Save Setup</button><Link className="ttm-primary" to="/dashboard/timetable">Next: Generate</Link></div>{saved && <p className="ttm-success">Setup saved. You can now generate a timetable draft.</p>}</section></Page>;
}

function Generate({ onGenerate }) {
  const [selected, setSelected] = useState(SECTIONS);
  const [busy, setBusy] = useState(false);
  const toggle = (section) => setSelected((items) => items.includes(section) ? items.filter((item) => item !== section) : [...items, section]);
  const generate = () => { if (!selected.length) return; setBusy(true); setTimeout(() => { onGenerate(selected); setBusy(false); }, 500); };
  return <Page title="Generate Timetable" subtitle="Generate a theory timetable for all selected sections together." action={<Link className="ttm-secondary" to="/dashboard/timetable/setup">Back: Setup</Link>}><section className="ttm-card ttm-generate"><div className="ttm-fields">{Object.entries(context).map(([key, value]) => <label key={key}>{key.replace(/([A-Z])/g, " $1")}<select defaultValue={value}><option>{value}</option></select></label>)}</div><h3>Sections</h3><div className="ttm-check-list">{SECTIONS.map((section) => <label key={section}><input type="checkbox" checked={selected.includes(section)} onChange={() => toggle(section)}/>{section}</label>)}</div><div className="ttm-info"><Sparkles/> Theory timetable only. Labs and practicals can be added manually after the draft is generated.</div><div className="ttm-screen-nav"><Link className="ttm-secondary" to="/dashboard/timetable/setup">Back</Link><button className="ttm-primary" disabled={!selected.length || busy} onClick={generate}>{busy ? "Generating draft…" : <><Sparkles/> Generate Timetable</>}</button></div></section></Page>;
}

function Draft({ slots, setSlots }) {
  const [section, setSection] = useState("MPC-A"); const [editing, setEditing] = useState(null); const [dialog, setDialog] = useState(null); const [status, setStatus] = useState("DRAFT");
  const visible = slots.filter((slot) => slot.section === section);
  const saveSlot = (slot) => setSlots((items) => items.some((item) => item.id === slot.id) ? items.map((item) => item.id === slot.id ? slot : item) : [...items, slot]);
  return <Page title="Timetable Draft" subtitle="Review, validate and publish the generated timetable." action={<div className="ttm-actions"><button className="ttm-secondary" onClick={() => setDialog("validate")}><ClipboardCheck/> Validate</button><button className="ttm-secondary" onClick={() => setStatus("DRAFT")}>Save Draft</button><button className="ttm-secondary" disabled={status !== "DRAFT"} onClick={() => setDialog("approve")}>Approve</button><button className="ttm-primary" disabled={status !== "APPROVED"} onClick={() => setDialog("publish")}><Send/> Publish</button></div>}><section className="ttm-card"><div className="ttm-draft-meta"><div><strong>{context.group} Group</strong><span>{context.academicYear} · {context.board}</span></div><b data-status={status}>{status}</b></div><div className="ttm-tabs">{SECTIONS.map((item) => <button className={item === section ? "active" : ""} key={item} onClick={() => setSection(item)}>{item}</button>)}</div><WeeklyGrid slots={visible} section={section} onEdit={setEditing}/><div className="ttm-screen-nav"><Link className="ttm-secondary" to="/dashboard/timetable">Back</Link><Link className="ttm-primary" to="/dashboard/timetable/faculty">Next</Link></div></section>{editing && <SlotEditor slot={editing} section={section} onClose={() => setEditing(null)} onSave={(slot) => { saveSlot(slot); setEditing(null); }}/>} {dialog === "validate" && <Validation onClose={() => setDialog(null)}/>} {dialog === "approve" && <Confirm title="Approve Timetable" text="Validation is successful. Approve this editable draft for all MPC sections?" confirm="Approve Draft" onClose={() => setDialog(null)} onConfirm={() => { setStatus("APPROVED"); setDialog(null); }}/>} {dialog === "publish" && <Confirm title="Publish Timetable" text="This approved timetable will become visible to students and faculty." confirm="Publish Now" onClose={() => setDialog(null)} onConfirm={() => { setStatus("PUBLISHED"); setDialog(null); }}/>}</Page>;
}

function WeeklyGrid({ slots, section, onEdit }) { return <div className="ttm-grid-wrap"><div className="ttm-grid"> <div className="ttm-grid-head">Period</div>{DAYS.map((day) => <div className="ttm-grid-head" key={day}>{day.slice(0,3)}</div>)}{PERIODS.map((period) => <><div className={`ttm-period ${period.type === "Break" ? "is-break" : ""}`} key={period.id}>{period.id}<small>{period.start}–{period.end}</small></div>{DAYS.map((day) => { const slot = slots.find((item) => item.period === period.id && item.day === day); return <div className={`ttm-cell ${period.type === "Break" ? "is-break" : ""}`} key={`${period.id}-${day}`}>{period.type === "Break" ? "BREAK" : slot ? <button className="ttm-slot" onClick={() => onEdit(slot)}><strong>{slot.subject}</strong><span>{slot.faculty}</span><small>{slot.room}</small><Edit3/></button> : <button className="ttm-empty-slot" onClick={() => onEdit({ id: `${section}-${day}-${period.id}`, section, day, period: period.id, subject: "Mathematics", faculty: "Ravi Kumar", room: ROOM[section], type: "Practical" })}><Plus/> Add lab</button>}</div>; })}</>)}</div></div>; }
function SlotEditor({ slot, section, onClose, onSave }) { const [value, setValue] = useState(slot); const eligible = FACULTY[value.subject] || []; return <Modal title={slot.type === "Practical" ? "Add Practical / Lab Slot" : "Edit Timetable Slot"} onClose={onClose}><div className="ttm-modal-body"><p><b>{section}</b> · {value.day} · {value.period}</p><label>Subject<Select value={value.subject} onChange={(subject) => setValue((item) => ({ ...item, subject, faculty: FACULTY[subject][0] }))} options={SUBJECTS}/></label><label>Faculty<Select value={value.faculty} onChange={(faculty) => setValue((item) => ({ ...item, faculty }))} options={eligible}/></label><label>Room<select value={value.room} onChange={(e) => setValue((item) => ({ ...item, room: e.target.value }))}><option>{ROOM[section]}</option><option>Physics Lab</option></select></label><p className="ttm-info">{value.type === "Practical" ? "Manual lab room selected." : `${ROOM[section]} is the section default room.`}</p><div className="ttm-actions"><button className="ttm-secondary" onClick={onClose}>Cancel</button><button className="ttm-primary" onClick={() => onSave(value)}>Save</button></div></div></Modal>; }
function Validation({ onClose }) { return <Modal title="Timetable Validation" onClose={onClose}><div className="ttm-modal-body"><ul className="ttm-validation"><li>✓ Faculty subject allocation</li><li>✓ Section conflicts</li><li>✓ Faculty conflicts</li><li>✓ Room conflicts</li><li>✓ Break periods</li></ul><div className="ttm-warning">⚠ Warning: MPC-B has two consecutive Physics periods.</div><button className="ttm-primary" onClick={onClose}>Done</button></div></Modal>; }
function Confirm({ title, text, confirm, onClose, onConfirm }) { return <Modal title={title} onClose={onClose}><div className="ttm-modal-body"><p>{text}</p><div className="ttm-actions"><button className="ttm-secondary" onClick={onClose}>Cancel</button><button className="ttm-primary" onClick={onConfirm}>{confirm}</button></div></div></Modal>; }
function Faculty({ slots }) { const [faculty, setFaculty] = useState("Ravi Kumar"); const schedule = slots.filter((slot) => slot.faculty === faculty); return <Page title="Faculty Timetable" subtitle="View the complete weekly schedule of a faculty member." action={<Link className="ttm-secondary" to="/dashboard/timetable/draft">Back: Draft</Link>}><section className="ttm-card"><div className="ttm-faculty-select"><label>Select Faculty<Select value={faculty} onChange={setFaculty} options={Object.values(FACULTY).flat()}/></label><div><GraduationCap/><strong>{faculty}</strong><span>{faculty === "Ravi Kumar" ? "Mathematics · FAC001" : "Faculty timetable"}</span></div></div><WeeklyGrid slots={schedule} section="Faculty" onEdit={() => {}}/><div className="ttm-screen-nav"><Link className="ttm-secondary" to="/dashboard/timetable/draft">Back</Link><Link className="ttm-primary" to="/dashboard/timetable">Finish</Link></div></section></Page>; }

export default function TimetablePage({ screen = "generate" }) { const [slots, setSlots] = useState(initialSlots); if (screen === "setup") return <Setup/>; if (screen === "draft") return <Draft slots={slots} setSlots={setSlots}/>; if (screen === "faculty") return <Faculty slots={slots}/>; return <Generate onGenerate={() => { window.location.assign("/dashboard/timetable/draft"); }}/>; }
