import * as data from "@/data/mockData.js";

const o = data.options;

// Central module configuration: columns + form fields + mock rows.
// Swap `rows` for an API response later without touching components.
export const modules = {
  boards: {
    title: "Board Management",
    subtitle: "Configure examination boards, academic patterns and grading rules.",
    breadcrumb: ["Academics"],
    addLabel: "Add Board",
    rows: data.boards,
    columns: [
      { key: "name", label: "Board Name", strong: true },
      { key: "code", label: "Board Code" },
      { key: "country", label: "Country" },
      { key: "state", label: "State" },
      { key: "structure", label: "Academic Structure" },
      { key: "status", label: "Status", badge: true },
      { key: "created", label: "Created Date" },
    ],
    fields: [
      { name: "name", label: "Board Name", required: true },
      { name: "code", label: "Board Code", required: true },
      { name: "description", label: "Description", type: "textarea", full: true },
      { name: "country", label: "Country", type: "select", options: ["India", "Nepal", "Sri Lanka"], required: true },
      { name: "state", label: "State", type: "select", options: ["Delhi", "Andhra Pradesh", "Telangana", "Maharashtra", "Karnataka", "West Bengal"], required: true },
      { name: "pattern", label: "Academic Pattern", type: "select", options: ["Annual", "Semester", "Trimester"], required: true },
      { name: "structure", label: "Academic Levels", type: "select", options: ["Intermediate", "10+2", "PUC", "Higher Secondary"], required: true },
      { name: "internal", label: "Internal Assessment", type: "checkbox", placeholder: "Enabled" },
      { name: "practical", label: "Practical Exams", type: "checkbox", placeholder: "Enabled" },
      { name: "boardExams", label: "Board Exams", type: "checkbox", placeholder: "Enabled" },
      { name: "passPercentage", label: "Pass Percentage", type: "number", required: true },
      { name: "grading", label: "Grading System", type: "select", options: ["Percentage", "Grade Points", "CGPA"], required: true },
      { name: "rank", label: "Rank Calculation", type: "select", options: ["Total Marks", "Percentage", "Grade Points"] },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  "academic-years": {
    title: "Academic Year",
    subtitle: "Define academic sessions and admission windows.",
    breadcrumb: ["Academics"],
    addLabel: "Add Academic Year",
    rows: data.academicYears,
    columns: [
      { key: "name", label: "Academic Year", strong: true },
      { key: "start", label: "Start Date" },
      { key: "end", label: "End Date" },
      { key: "admissionStart", label: "Admission Start" },
      { key: "admissionEnd", label: "Admission End" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "name", label: "Academic Year Name", required: true, placeholder: "2025-2026" },
      { name: "start", label: "Start Date", type: "date", required: true },
      { name: "end", label: "End Date", type: "date", required: true },
      { name: "admissionStart", label: "Admission Start Date", type: "date", required: true },
      { name: "admissionEnd", label: "Admission End Date", type: "date", required: true },
      { name: "status", label: "Active", type: "select", options: o.status, required: true },
    ],
  },

  courses: {
    title: "Course / Group Management",
    subtitle: "Manage streams and groups mapped to boards and academic levels.",
    breadcrumb: ["Academics"],
    addLabel: "Add Course",
    rows: data.courses,
    columns: [
      { key: "name", label: "Group Name", strong: true },
      { key: "code", label: "Group Code" },
      { key: "board", label: "Board" },
      { key: "level", label: "Academic Level" },
      { key: "subjects", label: "Total Subjects" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "year", label: "Academic Year", type: "select", options: o.year, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "name", label: "Group Name", required: true },
      { name: "code", label: "Group Code", required: true },
      { name: "description", label: "Description", type: "textarea", full: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  subjects: {
    title: "Subject Management",
    subtitle: "Subject master with internal, practical and external mark splits.",
    breadcrumb: ["Academics"],
    addLabel: "Add Subject",
    rows: data.subjects,
    columns: [
      { key: "name", label: "Subject Name", strong: true },
      { key: "code", label: "Subject Code" },
      { key: "group", label: "Group" },
      { key: "level", label: "Academic Level" },
      { key: "type", label: "Subject Type" },
      { key: "max", label: "Maximum Marks" },
      { key: "pass", label: "Passing Marks" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "name", label: "Subject Name", required: true },
      { name: "code", label: "Subject Code", required: true },
      { name: "type", label: "Subject Type", type: "select", options: o.subjectType, required: true },
      { name: "theory", label: "Theory", type: "checkbox", placeholder: "Applicable" },
      { name: "practicalFlag", label: "Practical", type: "checkbox", placeholder: "Applicable" },
      { name: "language", label: "Language", type: "checkbox", placeholder: "Language subject" },
      { name: "elective", label: "Elective", type: "checkbox", placeholder: "Elective subject" },
      { name: "internalMarks", label: "Internal Marks", type: "number", required: true },
      { name: "practicalMarks", label: "Practical Marks", type: "number" },
      { name: "externalMarks", label: "External Marks", type: "number", required: true },
      { name: "max", label: "Total Marks", type: "number", required: true },
      { name: "pass", label: "Passing Marks", type: "number", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  sections: {
    title: "Section Management",
    subtitle: "Class sections, rooms, class teachers and strength limits.",
    breadcrumb: ["Academics"],
    addLabel: "Add Section",
    rows: data.sections,
    columns: [
      { key: "name", label: "Section Name", strong: true },
      { key: "group", label: "Group" },
      { key: "level", label: "Academic Level" },
      { key: "room", label: "Room Number" },
      { key: "teacher", label: "Class Teacher" },
      { key: "strength", label: "Maximum Strength" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "year", label: "Academic Year", type: "select", options: o.year, required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "name", label: "Section Name", required: true },
      { name: "room", label: "Room Number", required: true },
      { name: "teacher", label: "Class Teacher", type: "select", options: o.faculty, required: true },
      { name: "strength", label: "Maximum Strength", type: "number", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  faculty: {
    title: "Faculty Management",
    subtitle: "Faculty master records, credentials and departments.",
    breadcrumb: ["People"],
    addLabel: "Add Faculty",
    rows: data.faculty,
    columns: [
      { key: "empId", label: "Employee ID", strong: true },
      { key: "name", label: "Faculty Name" },
      { key: "mobile", label: "Mobile" },
      { key: "email", label: "Email" },
      { key: "department", label: "Department" },
      { key: "designation", label: "Designation" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "empId", label: "Employee ID", required: true },
      { name: "firstName", label: "First Name", required: true },
      { name: "lastName", label: "Last Name", required: true },
      { name: "gender", label: "Gender", type: "select", options: o.gender, required: true },
      { name: "dob", label: "Date of Birth", type: "date", required: true },
      { name: "aadhaar", label: "Aadhaar Number" },
      { name: "mobile", label: "Mobile", type: "tel", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "bloodGroup", label: "Blood Group", type: "select", options: o.bloodGroup },
      { name: "qualification", label: "Qualification", required: true },
      { name: "designation", label: "Designation", required: true },
      { name: "department", label: "Department", type: "select", options: o.department, required: true },
      { name: "joining", label: "Joining Date", type: "date", required: true },
      { name: "experience", label: "Experience (years)", type: "number" },
      { name: "username", label: "Username", required: true },
      { name: "password", label: "Password", type: "password", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  "faculty-allocation": {
    title: "Faculty Subject Allocation",
    subtitle: "Map faculty to groups, sections and subjects.",
    breadcrumb: ["People"],
    addLabel: "Allocate Subject",
    rows: data.facultyAllocations,
    columns: [
      { key: "faculty", label: "Faculty", strong: true },
      { key: "board", label: "Board" },
      { key: "year", label: "Academic Year" },
      { key: "group", label: "Group" },
      { key: "level", label: "Academic Level" },
      { key: "section", label: "Section" },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "faculty", label: "Faculty", type: "select", options: o.faculty, required: true },
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "year", label: "Academic Year", type: "select", options: o.year, required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "section", label: "Section", type: "select", options: o.section, required: true },
      { name: "subject", label: "Subject", type: "select", options: o.subject, required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  assignments: {
    title: "Assignment & Study Materials",
    subtitle: "Publish assignments, attachments and due dates.",
    breadcrumb: ["Operations"],
    addLabel: "Create Assignment",
    rows: data.assignments,
    columns: [
      { key: "title", label: "Title", strong: true },
      { key: "subject", label: "Subject" },
      { key: "faculty", label: "Faculty" },
      { key: "due", label: "Due Date" },
      { key: "max", label: "Maximum Marks" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "subject", label: "Subject", type: "select", options: o.subject, required: true },
      { name: "faculty", label: "Faculty", type: "select", options: o.faculty, required: true },
      { name: "description", label: "Description", type: "textarea", full: true },
      { name: "due", label: "Due Date", type: "date", required: true },
      { name: "attachment", label: "Attachment", type: "file" },
      { name: "max", label: "Maximum Marks", type: "number", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  examinations: {
    title: "Examination Management",
    subtitle: "Create examinations and publish subject-wise schedules.",
    breadcrumb: ["Examinations"],
    addLabel: "Create Examination",
    rows: data.examinations,
    columns: [
      { key: "name", label: "Exam Name", strong: true },
      { key: "board", label: "Board" },
      { key: "year", label: "Academic Year" },
      { key: "level", label: "Academic Level" },
      { key: "group", label: "Group" },
      { key: "type", label: "Exam Type" },
      { key: "start", label: "Start Date" },
      { key: "end", label: "End Date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "name", label: "Exam Name", required: true },
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "year", label: "Academic Year", type: "select", options: o.year, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "type", label: "Exam Type", type: "select", options: o.examType, required: true },
      { name: "start", label: "Start Date", type: "date", required: true },
      { name: "end", label: "End Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
    secondary: {
      title: "Exam Schedule",
      addLabel: "Add Schedule",
      rows: data.examSchedule,
      columns: [
        { key: "subject", label: "Subject", strong: true },
        { key: "date", label: "Date" },
        { key: "time", label: "Time" },
        { key: "hall", label: "Hall" },
        { key: "invigilator", label: "Invigilator" },
        { key: "status", label: "Status", badge: true },
      ],
      fields: [
        { name: "subject", label: "Subject", type: "select", options: o.subject, required: true },
        { name: "date", label: "Date", type: "date", required: true },
        { name: "time", label: "Time", required: true, placeholder: "09:30 - 12:30" },
        { name: "hall", label: "Hall", required: true },
        { name: "invigilator", label: "Invigilator", type: "select", options: o.faculty, required: true },
        { name: "status", label: "Status", type: "select", options: o.status, required: true },
      ],
    },
  },

  "fee-structure": {
    title: "Fee Management",
    subtitle: "Fee structures and day-to-day fee collection.",
    breadcrumb: ["Administration"],
    addLabel: "Add Fee Structure",
    rows: data.fees,
    columns: [
      { key: "board", label: "Board", strong: true },
      { key: "year", label: "Academic Year" },
      { key: "group", label: "Group" },
      { key: "type", label: "Fee Type" },
      { key: "amount", label: "Amount", render: (r) => `₹${Number(r.amount).toLocaleString("en-IN")}` },
      { key: "due", label: "Due Date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "board", label: "Board", type: "select", options: o.board, required: true },
      { name: "year", label: "Academic Year", type: "select", options: o.year, required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "type", label: "Fee Type", type: "select", options: o.feeType, required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "due", label: "Due Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
    secondary: {
      title: "Fee Collection",
      addLabel: "Collect Fee",
      rows: data.feeCollections,
      columns: [
        { key: "receipt", label: "Receipt Number", strong: true },
        { key: "student", label: "Student" },
        { key: "date", label: "Payment Date" },
        { key: "amount", label: "Amount", render: (r) => `₹${Number(r.amount).toLocaleString("en-IN")}` },
        { key: "discount", label: "Discount" },
        { key: "fine", label: "Fine" },
        { key: "mode", label: "Payment Mode" },
        { key: "txn", label: "Transaction No." },
        { key: "status", label: "Status", badge: true },
      ],
      fields: [
        { name: "student", label: "Student", type: "select", options: o.student, required: true },
        { name: "receipt", label: "Receipt Number", required: true },
        { name: "date", label: "Payment Date", type: "date", required: true },
        { name: "amount", label: "Amount", type: "number", required: true },
        { name: "discount", label: "Discount", type: "number" },
        { name: "fine", label: "Fine", type: "number" },
        { name: "mode", label: "Payment Mode", type: "select", options: o.paymentMode, required: true },
        { name: "txn", label: "Transaction Number" },
        { name: "status", label: "Status", type: "select", options: o.status, required: true },
      ],
    },
  },

  certificates: {
    title: "Certificate Management",
    subtitle: "Issue and track student certificates.",
    breadcrumb: ["Administration"],
    addLabel: "Issue Certificate",
    rows: data.certificates,
    columns: [
      { key: "number", label: "Certificate Number", strong: true },
      { key: "student", label: "Student" },
      { key: "type", label: "Certificate Type" },
      { key: "purpose", label: "Purpose" },
      { key: "issue", label: "Issue Date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "student", label: "Student", type: "select", options: o.student, required: true },
      { name: "type", label: "Certificate Type", type: "select", options: o.certificateType, required: true },
      { name: "purpose", label: "Purpose", required: true },
      { name: "issue", label: "Issue Date", type: "date", required: true },
      { name: "remarks", label: "Remarks", type: "textarea", full: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },

  students: {
    title: "Student Management",
    subtitle: "Search students, view complete profiles and manage records.",
    breadcrumb: ["People"],
    addLabel: "Add Student",
    rows: data.students,
    columns: [
      { key: "admissionNo", label: "Admission No", strong: true },
      { key: "name", label: "Student Name" },
      { key: "roll", label: "Roll Number" },
      { key: "group", label: "Group" },
      { key: "level", label: "Academic Level" },
      { key: "section", label: "Section" },
      { key: "mobile", label: "Mobile" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "admissionNo", label: "Admission Number", required: true },
      { name: "name", label: "Student Name", required: true },
      { name: "roll", label: "Roll Number", required: true },
      { name: "group", label: "Group", type: "select", options: o.group, required: true },
      { name: "level", label: "Academic Level", type: "select", options: o.level, required: true },
      { name: "section", label: "Section", type: "select", options: ["A", "B", "C"], required: true },
      { name: "gender", label: "Gender", type: "select", options: o.gender, required: true },
      { name: "father", label: "Father Name", required: true },
      { name: "mobile", label: "Mobile", type: "tel", required: true },
      { name: "status", label: "Status", type: "select", options: o.status, required: true },
    ],
  },
};


